emlabcpp: emlabcpp::eabi_logger Class Reference
emlabcpp::eabi_logger Class Reference
#include <eabi_logger.h>
Public Member Functions
eabi_logger (const std::vector< logging_option > &opts)
void set_option (const logging_option &opt)
void log_header (const timelog &tl, const std::string_view file, const int line)
template<typename... Args>
void log (const Args &... args)
Constructor & Destructor Documentation
eabi_logger()
emlabcpp::eabi_logger::eabi_logger (const std::vector< logging_option > & opts) inline explicit
References set_option().
Member Function Documentation
log()
template<typename... Args> void emlabcpp::eabi_logger::log (const Args &... args) inline
References emlabcpp::args, and emlabcpp::reset_color().
log_header()
void emlabcpp::eabi_logger::log_header (const timelog & tl, const std::string_view file, const int line) inline
References emlabcpp::log_colors::file, emlabcpp::log_colors::line, and emlabcpp::log_colors::time.
set_option()
void emlabcpp::eabi_logger::set_option (const logging_option & opt) inline
References emlabcpp::set_stdout::enabled, emlabcpp::f, and emlabcpp::match().
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/logging/eabi_logger.h