emlabcpp: emlabcpp::pmr::stack_resource< Capacity > Class Template Reference
emlabcpp::pmr::stack_resource< Capacity > Class Template Reference final
#include <stack_resource.h>
Public Member Functions
stack_resource ()
stack_resource (const stack_resource &)=delete
stack_resource (stack_resource &&)=delete
stack_resource & operator= (const stack_resource &)=delete
stack_resource & operator= (stack_resource &&)=delete
void * allocate (const std::size_t bytes, const std::size_t alignment) override
result deallocate (void *const ptr, const std::size_t bytes, const std::size_t) override
bool is_equal (const pmr::memory_resource &other) const noexcept override
bool is_full () const noexcept override
~stack_resource () override=default
Public Member Functions inherited from emlabcpp::pmr::memory_resource
virtual ~memory_resource ()=default
Constructor & Destructor Documentation
stack_resource() [1/3]
template<std::size_t Capacity> emlabcpp::pmr::stack_resource< Capacity >::stack_resource () inline
stack_resource() [2/3]
template<std::size_t Capacity> emlabcpp::pmr::stack_resource< Capacity >::stack_resource (const stack_resource< Capacity > &) delete
stack_resource() [3/3]
template<std::size_t Capacity> emlabcpp::pmr::stack_resource< Capacity >::stack_resource (stack_resource< Capacity > &&) delete
~stack_resource()
template<std::size_t Capacity> emlabcpp::pmr::stack_resource< Capacity >::~stack_resource () override default
Member Function Documentation
allocate()
template<std::size_t Capacity> void* emlabcpp::pmr::stack_resource< Capacity >::allocate (const std::size_t bytes, const std::size_t alignment) inline override virtual
Implements emlabcpp::pmr::memory_resource.
References emlabcpp::pmr::align(), emlabcpp::bytes(), and EMLABCPP_DEBUG_LOG.
deallocate()
template<std::size_t Capacity> result emlabcpp::pmr::stack_resource< Capacity >::deallocate (void *const ptr, const std::size_t bytes, const std::size_t) inline override virtual
Implements emlabcpp::pmr::memory_resource.
References emlabcpp::bytes(), EMLABCPP_DEBUG_LOG, and emlabcpp::SUCCESS.
is_equal()
template<std::size_t Capacity> bool emlabcpp::pmr::stack_resource< Capacity >::is_equal (const pmr::memory_resource & other) const inline override virtual noexcept
Implements emlabcpp::pmr::memory_resource.
is_full()
template<std::size_t Capacity> bool emlabcpp::pmr::stack_resource< Capacity >::is_full () const inline override virtual noexcept
Implements emlabcpp::pmr::memory_resource.
operator=() [1/2]
template<std::size_t Capacity> stack_resource& emlabcpp::pmr::stack_resource< Capacity >::operator= (const stack_resource< Capacity > &) delete
operator=() [2/2]
template<std::size_t Capacity> stack_resource& emlabcpp::pmr::stack_resource< Capacity >::operator= (stack_resource< Capacity > &&) delete
The documentation for this class was generated from the following file:
include/emlabcpp/pmr/stack_resource.h