emlabcpp: emlabcpp::pool_resource< PoolSize, PoolCount > Class Template Reference
emlabcpp::pool_resource< PoolSize, PoolCount > Class Template Reference final
#include <pool.h>
Public Member Functions
pool_resource ()
pool_resource (const pool_resource &)=delete
pool_resource (pool_resource &&)=delete
pool_resource & operator= (const pool_resource &)=delete
pool_resource & operator= (pool_resource &&)=delete
void * allocate (std::size_t bytes, std::size_t alignment) final
void deallocate (void *ptr) final
bool full () final
~pool_resource () final=default
Public Member Functions inherited from emlabcpp::pool_interface
virtual ~pool_interface ()=default
Constructor & Destructor Documentation
pool_resource() [1/3]
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pool_resource< PoolSize, PoolCount >::pool_resource () inline
References emlabcpp::static_vector< T, N >::push_back(), and emlabcpp::range().
pool_resource() [2/3]
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pool_resource< PoolSize, PoolCount >::pool_resource (const pool_resource< PoolSize, PoolCount > &) delete
pool_resource() [3/3]
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pool_resource< PoolSize, PoolCount >::pool_resource (pool_resource< PoolSize, PoolCount > &&) delete
~pool_resource()
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pool_resource< PoolSize, PoolCount >::~pool_resource () final default
Member Function Documentation
allocate()
template<std::size_t PoolSize, uint16_t PoolCount> void* emlabcpp::pool_resource< PoolSize, PoolCount >::allocate (std::size_t bytes, std::size_t alignment) inline final virtual
Implements emlabcpp::pool_interface.
References emlabcpp::align(), emlabcpp::static_vector< T, N >::back(), EMLABCPP_ASSERT, emlabcpp::static_vector< T, N >::empty(), and emlabcpp::static_vector< T, N >::pop_back().
deallocate()
template<std::size_t PoolSize, uint16_t PoolCount> void emlabcpp::pool_resource< PoolSize, PoolCount >::deallocate (void * ptr) inline final virtual
Implements emlabcpp::pool_interface.
References EMLABCPP_ASSERT, and emlabcpp::static_vector< T, N >::push_back().
full()
template<std::size_t PoolSize, uint16_t PoolCount> bool emlabcpp::pool_resource< PoolSize, PoolCount >::full () inline final virtual
Implements emlabcpp::pool_interface.
References emlabcpp::static_vector< T, N >::empty().
operator=() [1/2]
template<std::size_t PoolSize, uint16_t PoolCount> pool_resource& emlabcpp::pool_resource< PoolSize, PoolCount >::operator= (const pool_resource< PoolSize, PoolCount > &) delete
operator=() [2/2]
template<std::size_t PoolSize, uint16_t PoolCount> pool_resource& emlabcpp::pool_resource< PoolSize, PoolCount >::operator= (pool_resource< PoolSize, PoolCount > &&) delete
The documentation for this class was generated from the following file:
include/emlabcpp/allocator/pool.h