emlabcpp: emlabcpp::coro::recursive_coroutine< T > Class Template Reference
emlabcpp::coro::recursive_coroutine< T > Class Template Reference
#include <recursive.h>
Classes
struct promise_type
Public Types
using handle = std::coroutine_handle< promise_type >
using owning_handle = owning_coroutine_handle< promise_type >
Public Member Functions
recursive_coroutine ()=default
recursive_coroutine (const handle &cor)
bool done () const
wait_state get_state () const override
bool await_ready () const
template<typename U >
void await_suspend (const U h)
auto await_resume ()
auto get_value ()
auto run ()
void tick () override
Public Member Functions inherited from emlabcpp::coro::wait_interface
virtual ~wait_interface ()=default
Member Typedef Documentation
handle
template<typename T > using emlabcpp::coro::recursive_coroutine< T >::handle = std::coroutine_handle< promise_type >
owning_handle
template<typename T > using emlabcpp::coro::recursive_coroutine< T >::owning_handle = owning_coroutine_handle< promise_type >
Constructor & Destructor Documentation
recursive_coroutine() [1/2]
template<typename T > emlabcpp::coro::recursive_coroutine< T >::recursive_coroutine () default
recursive_coroutine() [2/2]
template<typename T > emlabcpp::coro::recursive_coroutine< T >::recursive_coroutine (const handle & cor) inline explicit
Member Function Documentation
await_ready()
template<typename T > bool emlabcpp::coro::recursive_coroutine< T >::await_ready () const inline
await_resume()
template<typename T > auto emlabcpp::coro::recursive_coroutine< T >::await_resume () inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), and emlabcpp::coro::data_promise< T >::value.
await_suspend()
template<typename T > template<typename U > void emlabcpp::coro::recursive_coroutine< T >::await_suspend (const U h) inline
done()
template<typename T > bool emlabcpp::coro::recursive_coroutine< T >::done () const inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done().
get_state()
template<typename T > wait_state emlabcpp::coro::recursive_coroutine< T >::get_state () const inline override virtual
Implements emlabcpp::coro::wait_interface.
References emlabcpp::coro::recursive_coroutine< T >::done(), emlabcpp::coro::READY, and emlabcpp::coro::WAITING.
get_value()
template<typename T > auto emlabcpp::coro::recursive_coroutine< T >::get_value () inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), and emlabcpp::coro::data_promise< T >::value.
run()
template<typename T > auto emlabcpp::coro::recursive_coroutine< T >::run () inline
References emlabcpp::coro::recursive_coroutine< T >::done(), emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), emlabcpp::coro::recursive_coroutine< T >::tick(), and emlabcpp::coro::data_promise< T >::value.
tick()
template<typename T > void emlabcpp::coro::recursive_coroutine< T >::tick () inline override virtual
Implements emlabcpp::coro::wait_interface.
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done(), EMLABCPP_ERROR_LOG, emlabcpp::coro::ERRORED, emlabcpp::coro::wait_interface::get_state(), emlabcpp::coro::recursive_coroutine< T >::promise_type::iface, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), emlabcpp::coro::wait_interface::tick(), and emlabcpp::coro::WAITING.
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/coro/recursive.h