emlabcpp: emlabcpp::pmr::pool_resource< PoolSize, PoolCount > Class Template Reference
emlabcpp::pmr::pool_resource< PoolSize, PoolCount > Class Template Reference final
#include <pool_resource.h>
Public Member Functions
pool_resource ()
pool_resource (const pool_resource &)=delete
pool_resource (pool_resource &&)=delete
pool_resource & operator= (const pool_resource &)=delete
pool_resource & operator= (pool_resource &&)=delete
void * allocate (const std::size_t bytes, const std::size_t alignment) override
bool deallocate (void *const ptr, const std::size_t, const std::size_t) override
bool is_equal (const pmr::memory_resource &other) const noexcept override
bool is_full () const override
~pool_resource () override=default
Public Member Functions inherited from emlabcpp::pmr::memory_resource
virtual ~memory_resource ()=default
Constructor & Destructor Documentation
pool_resource() [1/3]
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::pool_resource () inline
References emlabcpp::static_vector< T, N >::push_back(), and emlabcpp::range().
pool_resource() [2/3]
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::pool_resource (const pool_resource< PoolSize, PoolCount > &) delete
pool_resource() [3/3]
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::pool_resource (pool_resource< PoolSize, PoolCount > &&) delete
~pool_resource()
template<std::size_t PoolSize, uint16_t PoolCount> emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::~pool_resource () override default
Member Function Documentation
allocate()
template<std::size_t PoolSize, uint16_t PoolCount> void* emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::allocate (const std::size_t bytes, const std::size_t alignment) inline override virtual
Implements emlabcpp::pmr::memory_resource.
References emlabcpp::pmr::align(), emlabcpp::static_vector< T, N >::back(), emlabcpp::bytes(), EMLABCPP_ERROR_LOG, emlabcpp::static_vector< T, N >::empty(), and emlabcpp::static_vector< T, N >::pop_back().
deallocate()
template<std::size_t PoolSize, uint16_t PoolCount> bool emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::deallocate (void *const ptr, const std::size_t , const std::size_t) inline override virtual
Implements emlabcpp::pmr::memory_resource.
References EMLABCPP_ERROR_LOG, and emlabcpp::static_vector< T, N >::push_back().
is_equal()
template<std::size_t PoolSize, uint16_t PoolCount> bool emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::is_equal (const pmr::memory_resource & other) const inline override virtual noexcept
Implements emlabcpp::pmr::memory_resource.
is_full()
template<std::size_t PoolSize, uint16_t PoolCount> bool emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::is_full () const inline override virtual
Implements emlabcpp::pmr::memory_resource.
References emlabcpp::static_vector< T, N >::empty().
operator=() [1/2]
template<std::size_t PoolSize, uint16_t PoolCount> pool_resource& emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::operator= (const pool_resource< PoolSize, PoolCount > &) delete
operator=() [2/2]
template<std::size_t PoolSize, uint16_t PoolCount> pool_resource& emlabcpp::pmr::pool_resource< PoolSize, PoolCount >::operator= (pool_resource< PoolSize, PoolCount > &&) delete
The documentation for this class was generated from the following file:
include/emlabcpp/pmr/pool_resource.h