emlabcpp: emlabcpp::static_storage< T, N > Class Template Reference
emlabcpp::static_storage< T, N > Class Template Reference
Continuous data container that can contain N of uninitialized elements.
#include <static_storage.h>
Public Types
using value_type = T
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
using size_type = std::size_t
Public Member Functions
pointer data () noexcept
Returns pointer to first item of the storage.
const_pointer data () const noexcept
Returns pointer to first item of the storage.
template<typename... Args>
constexpr void emplace_item (const size_type i, Args &&... args)
Constructs an item at position i with arguments args...
constexpr void delete_item (const size_type i)
Deconstructs an item at position i.
constexpr reference operator[] (const size_type i) noexcept
Provides a reference to item at position i.
constexpr const_reference operator[] (const size_type i) const noexcept
Provides a reference to item at position i.
Static Public Attributes
static constexpr std::size_t capacity = N
Detailed Description
template<typename T, std::size_t N>
class emlabcpp::static_storage< T, N >
Continuous data container that can contain N of uninitialized elements.
Bookkeeping (what item is initialized and what is not) is up to owner of this structure.
Member Typedef Documentation
const_pointer
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::const_pointer = const T*
const_reference
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::const_reference = const T&
pointer
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::pointer = T*
reference
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::reference = T&
size_type
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::size_type = std::size_t
value_type
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::value_type = T
Member Function Documentation
data() [1/2]
template<typename T , std::size_t N> const_pointer emlabcpp::static_storage< T, N >::data () const inline noexcept
Returns pointer to first item of the storage.
data() [2/2]
template<typename T , std::size_t N> pointer emlabcpp::static_storage< T, N >::data () inline noexcept
Returns pointer to first item of the storage.
delete_item()
template<typename T , std::size_t N> constexpr void emlabcpp::static_storage< T, N >::delete_item (const size_type i) inline constexpr
Deconstructs an item at position i.
References emlabcpp::static_storage< T, N >::data().
emplace_item()
template<typename T , std::size_t N> template<typename... Args> constexpr void emlabcpp::static_storage< T, N >::emplace_item (const size_type i, Args &&... args) inline constexpr
Constructs an item at position i with arguments args...
References emlabcpp::args, and emlabcpp::static_storage< T, N >::data().
operator[]() [1/2]
template<typename T , std::size_t N> constexpr const_reference emlabcpp::static_storage< T, N >::operator[] (const size_type i) const inline constexpr noexcept
Provides a reference to item at position i.
References emlabcpp::static_storage< T, N >::data().
operator[]() [2/2]
template<typename T , std::size_t N> constexpr reference emlabcpp::static_storage< T, N >::operator[] (const size_type i) inline constexpr noexcept
Provides a reference to item at position i.
References emlabcpp::static_storage< T, N >::data().
Member Data Documentation
capacity
template<typename T , std::size_t N> constexpr std::size_t emlabcpp::static_storage< T, N >::capacity = N static constexpr
The documentation for this class was generated from the following file:
include/emlabcpp/static_storage.h