emlabcpp: emlabcpp::testing::collector Class Reference
emlabcpp::testing::collector Class Reference
#include <collect.h>
Public Member Functions
collector (protocol::channel_type chann, collect_client_transmit_callback send_cb)
collector (collector const &)=delete
collector (collector &&)=delete
collector & operator= (collector const &)=delete
collector & operator= (collector &&)=delete
constexpr protocol::channel_type get_channel () const
outcome on_msg (std::span< std::byte const > const &msg)
outcome on_msg (collect_server_client_group const &var)
collect_awaiter set (node_id const parent, std::string_view key, contiguous_container_type t)
bool set (node_id const parent, std::string_view key, value_type const &val)
collect_awaiter set (std::string_view key, contiguous_container_type t)
bool set (std::string_view key, value_type const &val)
template<typename Arg >
bool set (node_id parent, std::string_view key, Arg const &arg)
template<typename Arg >
bool set (std::string_view key, Arg const &arg)
collect_awaiter append (node_id const parent, contiguous_container_type t)
bool append (node_id const parent, value_type const &val)
template<typename Arg >
bool append (node_id parent, Arg const &arg)
bool exchange (collect_request const &req, collect_reply_callback cb)
Constructor & Destructor Documentation
collector() [1/3]
emlabcpp::testing::collector::collector (protocol::channel_type chann, collect_client_transmit_callback send_cb)
collector() [2/3]
emlabcpp::testing::collector::collector (collector const &) delete
collector() [3/3]
emlabcpp::testing::collector::collector (collector &&) delete
Member Function Documentation
append() [1/3]
collect_awaiter emlabcpp::testing::collector::append (node_id const parent, contiguous_container_type t)
append() [2/3]
bool emlabcpp::testing::collector::append (node_id const parent, value_type const & val)
append() [3/3]
template<typename Arg > bool emlabcpp::testing::collector::append (node_id parent, Arg const & arg) inline
References append().
exchange()
bool emlabcpp::testing::collector::exchange (collect_request const & req, collect_reply_callback cb)
get_channel()
constexpr protocol::channel_type emlabcpp::testing::collector::get_channel () const inline constexpr
on_msg() [1/2]
outcome emlabcpp::testing::collector::on_msg (collect_server_client_group const & var)
on_msg() [2/2]
outcome emlabcpp::testing::collector::on_msg (std::span< std::byte const > const & msg)
operator=() [1/2]
collector& emlabcpp::testing::collector::operator= (collector &&) delete
operator=() [2/2]
collector& emlabcpp::testing::collector::operator= (collector const &) delete
set() [1/6]
collect_awaiter emlabcpp::testing::collector::set (node_id const parent, std::string_view key, contiguous_container_type t)
set() [2/6]
bool emlabcpp::testing::collector::set (node_id const parent, std::string_view key, value_type const & val)
set() [3/6]
template<typename Arg > bool emlabcpp::testing::collector::set (node_id parent, std::string_view key, Arg const & arg) inline
References set().
set() [4/6]
template<typename Arg > bool emlabcpp::testing::collector::set (std::string_view key, Arg const & arg) inline
References set().
set() [5/6]
collect_awaiter emlabcpp::testing::collector::set (std::string_view key, contiguous_container_type t) inline
References set().
set() [6/6]
bool emlabcpp::testing::collector::set (std::string_view key, value_type const & val) inline
References set().
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/collect.h