emlabcpp: emlabcpp::protocol::message< N > Class Template Reference
emlabcpp::protocol::message< N > Class Template Reference
Protocol library has custom type that represents message, however this is just simple overaly over std::array that remembers how many bytes are used.
#include <message.h>
Public Types
using value_type = uint8_t
using iterator = uint8_t *
using const_iterator = const uint8_t *
Public Member Functions
message ()=default
template<std::size_t M>
message (const message< M > &other) noexcept
template<std::size_t M>
message (const std::array< uint8_t, M > &inpt) noexcept
template<std::convertible_to< uint8_t >... Ts>
message (Ts... inpt) noexcept
std::size_t size () const
uint8_t front () const
uint8_t & front ()
uint8_t back () const
uint8_t & back ()
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
uint8_t operator[] (std::size_t i) const
uint8_t & operator[] (std::size_t i)
template<std::size_t M>
operator std::array< uint8_t, M > () const
Static Public Member Functions
static std::optional< message > make (const range_container auto &cont)
Static Public Attributes
static constexpr std::size_t max_size = N
static constexpr std::size_t capacity = N
Protected Member Functions
template<typename Iterator >
message (Iterator beg, Iterator end) noexcept
Friends
auto operator== (const message &lh, const message &rh)
Detailed Description
template<std::size_t N>
class emlabcpp::protocol::message< N >
Protocol library has custom type that represents message, however this is just simple overaly over std::array that remembers how many bytes are used.
Member Typedef Documentation
const_iterator
template<std::size_t N> using emlabcpp::protocol::message< N >::const_iterator = const uint8_t*
iterator
template<std::size_t N> using emlabcpp::protocol::message< N >::iterator = uint8_t*
value_type
template<std::size_t N> using emlabcpp::protocol::message< N >::value_type = uint8_t
Constructor & Destructor Documentation
message() [1/5]
template<std::size_t N> emlabcpp::protocol::message< N >::message () default
message() [2/5]
template<std::size_t N> template<std::size_t M> emlabcpp::protocol::message< N >::message (const message< M > & other) inline explicit noexcept
message() [3/5]
template<std::size_t N> template<std::size_t M> emlabcpp::protocol::message< N >::message (const std::array< uint8_t, M > & inpt) inline explicit noexcept
message() [4/5]
template<std::size_t N> template<std::convertible_to< uint8_t >... Ts> emlabcpp::protocol::message< N >::message (Ts... inpt) inline explicit noexcept
message() [5/5]
template<std::size_t N> template<typename Iterator > emlabcpp::protocol::message< N >::message (Iterator beg, Iterator end) inline protected noexcept
References emlabcpp::protocol::message< N >::begin(), and emlabcpp::protocol::message< N >::end().
Member Function Documentation
back() [1/2]
template<std::size_t N> uint8_t& emlabcpp::protocol::message< N >::back () inline
back() [2/2]
template<std::size_t N> uint8_t emlabcpp::protocol::message< N >::back () const inline
begin() [1/2]
template<std::size_t N> iterator emlabcpp::protocol::message< N >::begin () inline
begin() [2/2]
template<std::size_t N> const_iterator emlabcpp::protocol::message< N >::begin () const inline
end() [1/2]
template<std::size_t N> iterator emlabcpp::protocol::message< N >::end () inline
end() [2/2]
template<std::size_t N> const_iterator emlabcpp::protocol::message< N >::end () const inline
front() [1/2]
template<std::size_t N> uint8_t& emlabcpp::protocol::message< N >::front () inline
front() [2/2]
template<std::size_t N> uint8_t emlabcpp::protocol::message< N >::front () const inline
make()
template<std::size_t N> static std::optional< message > emlabcpp::protocol::message< N >::make (const range_container auto & cont) inline static
References emlabcpp::protocol::message< N >::message(), and EMLABCPP_LOG.
operator std::array< uint8_t, M >()
template<std::size_t N> template<std::size_t M> emlabcpp::protocol::message< N >::operator std::array< uint8_t, M > () const inline explicit
References emlabcpp::protocol::message< N >::begin(), emlabcpp::protocol::message< N >::end(), and emlabcpp::res.
operator[]() [1/2]
template<std::size_t N> uint8_t& emlabcpp::protocol::message< N >::operator[] (std::size_t i) inline
operator[]() [2/2]
template<std::size_t N> uint8_t emlabcpp::protocol::message< N >::operator[] (std::size_t i) const inline
size()
template<std::size_t N> std::size_t emlabcpp::protocol::message< N >::size () const inline
Friends And Related Function Documentation
operator==
template<std::size_t N> auto operator== (const message< N > & lh, const message< N > & rh) friend
Member Data Documentation
capacity
template<std::size_t N> constexpr std::size_t emlabcpp::protocol::message< N >::capacity = N static constexpr
max_size
template<std::size_t N> constexpr std::size_t emlabcpp::protocol::message< N >::max_size = N static constexpr
The documentation for this class was generated from the following file:
include/emlabcpp/protocol/message.h