emlabcpp: emlabcpp::testing::record Class Reference
emlabcpp::testing::record Class Reference
#include <record.h>
Public Member Functions
record (test_id, run_id rid, reactor_interface_adapter &comm)
param_type_awaiter get_param_type (node_id)
template<typename T >
param_value_awaiter< T > get_param (node_id node)
template<typename T >
param_value_key_awaiter< T > get_param (node_id node, child_id chid)
template<typename T >
param_value_key_awaiter< T > get_param (node_id node, const key_type &k)
template<typename T >
param_value_key_awaiter< T > get_param (node_id node, std::string_view k)
param_child_awaiter get_param_child (node_id, child_id)
param_child_awaiter get_param_child (node_id, const key_type &key)
param_child_awaiter get_param_child (node_id, std::string_view key)
param_child_count_awaiter get_param_child_count (std::optional< node_id >)
param_child_count_awaiter get_param_child_count (node_id nid)
param_key_awaiter get_param_key (node_id, child_id)
bool errored ()
collect_awaiter collect (node_id parent, const std::optional< key_type > &key, const collect_value_type &arg, bool expects_reply=true)
collect_awaiter collect (node_id parent, const collect_value_type &arg, bool expects_reply=true)
collect_awaiter collect (node_id parent, std::string_view k, contiguous_container_type t, bool expects_reply=true)
collect_awaiter collect (node_id parent, contiguous_container_type t, bool expects_reply=true)
template<typename Arg >
collect_awaiter collect (node_id parent, std::string_view k, const Arg &arg, bool expects_reply=true)
template<typename Arg >
collect_awaiter collect (node_id parent, const Arg &arg, bool expects_reply=true)
void fail ()
void success ()
void expect (bool val)
Constructor & Destructor Documentation
record()
emlabcpp::testing::record::record (test_id , run_id rid, reactor_interface_adapter & comm) inline
Member Function Documentation
collect() [1/6]
template<typename Arg > collect_awaiter emlabcpp::testing::record::collect (node_id parent, const Arg & arg, bool expects_reply = true) inline
References collect().
collect() [2/6]
collect_awaiter emlabcpp::testing::record::collect (node_id parent, const collect_value_type & arg, bool expects_reply = true)
collect() [3/6]
collect_awaiter emlabcpp::testing::record::collect (node_id parent, const std::optional< key_type > & key, const collect_value_type & arg, bool expects_reply = true)
collect() [4/6]
collect_awaiter emlabcpp::testing::record::collect (node_id parent, contiguous_container_type t, bool expects_reply = true)
collect() [5/6]
template<typename Arg > collect_awaiter emlabcpp::testing::record::collect (node_id parent, std::string_view k, const Arg & arg, bool expects_reply = true) inline
References collect().
collect() [6/6]
collect_awaiter emlabcpp::testing::record::collect (node_id parent, std::string_view k, contiguous_container_type t, bool expects_reply = true)
errored()
bool emlabcpp::testing::record::errored () inline
expect()
void emlabcpp::testing::record::expect (bool val) inline
References fail(), and success().
fail()
void emlabcpp::testing::record::fail () inline
get_param() [1/4]
template<typename T > param_value_awaiter< T > emlabcpp::testing::record::get_param (node_id node) inline
get_param() [2/4]
template<typename T > param_value_key_awaiter< T > emlabcpp::testing::record::get_param (node_id node, child_id chid) inline
get_param() [3/4]
template<typename T > param_value_key_awaiter< T > emlabcpp::testing::record::get_param (node_id node, const key_type & k) inline
get_param() [4/4]
template<typename T > param_value_key_awaiter< T > emlabcpp::testing::record::get_param (node_id node, std::string_view k) inline
References emlabcpp::testing::key_type_to_buffer().
get_param_child() [1/3]
param_child_awaiter emlabcpp::testing::record::get_param_child (node_id , child_id)
get_param_child() [2/3]
param_child_awaiter emlabcpp::testing::record::get_param_child (node_id , const key_type & key)
get_param_child() [3/3]
param_child_awaiter emlabcpp::testing::record::get_param_child (node_id , std::string_view key)
get_param_child_count() [1/2]
param_child_count_awaiter emlabcpp::testing::record::get_param_child_count (node_id nid) inline
References get_param_child_count().
get_param_child_count() [2/2]
param_child_count_awaiter emlabcpp::testing::record::get_param_child_count (std::optional< node_id >)
get_param_key()
param_key_awaiter emlabcpp::testing::record::get_param_key (node_id , child_id)
get_param_type()
param_type_awaiter emlabcpp::testing::record::get_param_type (node_id)
success()
void emlabcpp::testing::record::success () inline
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/record.h