emlabcpp: emlabcpp::testing_record Class Reference
emlabcpp::testing_record Class Reference
#include <record.h>
Public Member Functions
testing_record (testing_test_id tid, testing_run_id rid, testing_reactor_interface_adapter &comm)
std::optional< testing_node_type > get_param_type (testing_node_id)
template<typename T >
std::optional< T > get_param (testing_node_id node)
template<typename T , typename Key >
std::optional< T > get_param (testing_node_id node, const Key &k)
template<typename T , typename Key >
std::optional< T > get_param (std::optional< testing_node_id > node, const Key &k)
std::optional< testing_value > get_param_value (testing_node_id param)
std::optional< testing_node_id > get_param_child (testing_node_id, testing_child_id)
std::optional< testing_node_id > get_param_child (testing_node_id, const testing_key &key)
std::optional< testing_node_id > get_param_child (testing_node_id, std::string_view key)
std::optional< testing_child_count > get_param_child_count (std::optional< testing_node_id >)
std::optional< testing_child_count > get_param_child_count (testing_node_id nid)
std::optional< testing_key > get_param_key (testing_node_id, testing_child_id)
bool errored ()
std::optional< testing_node_id > collect (testing_node_id parent, const std::optional< testing_key > &key, const testing_collect_arg &arg)
std::optional< testing_node_id > collect (testing_node_id parent, const testing_collect_arg &arg)
std::optional< testing_node_id > collect (testing_node_id parent, std::string_view k, contiguous_container_type t)
std::optional< testing_node_id > collect (testing_node_id parent, contiguous_container_type t)
template<typename Arg >
std::optional< testing_node_id > collect (testing_node_id parent, std::string_view k, const Arg &arg)
template<typename Arg >
std::optional< testing_node_id > collect (testing_node_id parent, const Arg &arg)
void fail ()
void success ()
void expect (bool val)
Constructor & Destructor Documentation
testing_record()
emlabcpp::testing_record::testing_record (testing_test_id tid, testing_run_id rid, testing_reactor_interface_adapter & comm) inline
Member Function Documentation
collect() [1/6]
template<typename Arg > std::optional< testing_node_id > emlabcpp::testing_record::collect (testing_node_id parent, const Arg & arg) inline
References collect().
collect() [2/6]
std::optional< testing_node_id > emlabcpp::testing_record::collect (testing_node_id parent, const std::optional< testing_key > & key, const testing_collect_arg & arg)
collect() [3/6]
std::optional< testing_node_id > emlabcpp::testing_record::collect (testing_node_id parent, const testing_collect_arg & arg)
collect() [4/6]
std::optional< testing_node_id > emlabcpp::testing_record::collect (testing_node_id parent, contiguous_container_type t) inline
References collect().
collect() [5/6]
template<typename Arg > std::optional< testing_node_id > emlabcpp::testing_record::collect (testing_node_id parent, std::string_view k, const Arg & arg) inline
References collect().
collect() [6/6]
std::optional< testing_node_id > emlabcpp::testing_record::collect (testing_node_id parent, std::string_view k, contiguous_container_type t) inline
References collect().
errored()
bool emlabcpp::testing_record::errored () inline
expect()
void emlabcpp::testing_record::expect (bool val) inline
References fail(), and success().
fail()
void emlabcpp::testing_record::fail () inline
get_param() [1/3]
template<typename T , typename Key > std::optional< T > emlabcpp::testing_record::get_param (std::optional< testing_node_id > node, const Key & k) inline
get_param() [2/3]
template<typename T > std::optional< T > emlabcpp::testing_record::get_param (testing_node_id node) inline
References EMLABCPP_LOG, and get_param_value().
get_param() [3/3]
template<typename T , typename Key > std::optional< T > emlabcpp::testing_record::get_param (testing_node_id node, const Key & k) inline
References EMLABCPP_LOG, and get_param_child().
get_param_child() [1/3]
std::optional< testing_node_id > emlabcpp::testing_record::get_param_child (testing_node_id , const testing_key & key)
get_param_child() [2/3]
std::optional< testing_node_id > emlabcpp::testing_record::get_param_child (testing_node_id , std::string_view key)
get_param_child() [3/3]
std::optional< testing_node_id > emlabcpp::testing_record::get_param_child (testing_node_id , testing_child_id)
get_param_child_count() [1/2]
std::optional< testing_child_count > emlabcpp::testing_record::get_param_child_count (std::optional< testing_node_id >)
get_param_child_count() [2/2]
std::optional< testing_child_count > emlabcpp::testing_record::get_param_child_count (testing_node_id nid) inline
References get_param_child_count().
get_param_key()
std::optional< testing_key > emlabcpp::testing_record::get_param_key (testing_node_id , testing_child_id)
get_param_type()
std::optional< testing_node_type > emlabcpp::testing_record::get_param_type (testing_node_id)
get_param_value()
std::optional< testing_value > emlabcpp::testing_record::get_param_value (testing_node_id param)
success()
void emlabcpp::testing_record::success () inline
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/record.h