emlabcpp: emlabcpp::coro::request_reply< RequestType, ReplyType > Class Template Reference
emlabcpp::coro::request_reply< RequestType, ReplyType > Class Template Reference
#include <request_reply.h>
Classes
struct awaiter
struct promise_type
Public Types
using request_type = RequestType
using reply_type = ReplyType
using handle = std::coroutine_handle< promise_type >
using owning_handle = owning_coroutine_handle< promise_type >
Public Member Functions
request_reply ()=default
request_reply (const handle cor)
request_reply (const request_reply &)=delete
request_reply & operator= (const request_reply &)=delete
request_reply (request_reply &&) noexcept=default
request_reply & operator= (request_reply &&) noexcept=default
const RequestType * get_request ()
bool has_reply ()
void store_reply (const ReplyType &inpt)
operator bool () const
bool done () const
bool tick ()
void * address () const
Member Typedef Documentation
handle
template<typename RequestType , typename ReplyType > using emlabcpp::coro::request_reply< RequestType, ReplyType >::handle = std::coroutine_handle< promise_type >
owning_handle
template<typename RequestType , typename ReplyType > using emlabcpp::coro::request_reply< RequestType, ReplyType >::owning_handle = owning_coroutine_handle< promise_type >
reply_type
template<typename RequestType , typename ReplyType > using emlabcpp::coro::request_reply< RequestType, ReplyType >::reply_type = ReplyType
request_type
template<typename RequestType , typename ReplyType > using emlabcpp::coro::request_reply< RequestType, ReplyType >::request_type = RequestType
Constructor & Destructor Documentation
request_reply() [1/4]
template<typename RequestType , typename ReplyType > emlabcpp::coro::request_reply< RequestType, ReplyType >::request_reply () default
request_reply() [2/4]
template<typename RequestType , typename ReplyType > emlabcpp::coro::request_reply< RequestType, ReplyType >::request_reply (const handle cor) inline
request_reply() [3/4]
template<typename RequestType , typename ReplyType > emlabcpp::coro::request_reply< RequestType, ReplyType >::request_reply (const request_reply< RequestType, ReplyType > &) delete
request_reply() [4/4]
template<typename RequestType , typename ReplyType > emlabcpp::coro::request_reply< RequestType, ReplyType >::request_reply (request_reply< RequestType, ReplyType > &&) default noexcept
Member Function Documentation
address()
template<typename RequestType , typename ReplyType > void* emlabcpp::coro::request_reply< RequestType, ReplyType >::address () const inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::address().
done()
template<typename RequestType , typename ReplyType > bool emlabcpp::coro::request_reply< RequestType, ReplyType >::done () const inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done().
get_request()
template<typename RequestType , typename ReplyType > const RequestType* emlabcpp::coro::request_reply< RequestType, ReplyType >::get_request () inline
References EMLABCPP_ERROR_LOG, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), and emlabcpp::coro::request_reply< RequestType, ReplyType >::promise_type::request.
has_reply()
template<typename RequestType , typename ReplyType > bool emlabcpp::coro::request_reply< RequestType, ReplyType >::has_reply () inline
References EMLABCPP_ERROR_LOG, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), and emlabcpp::coro::request_reply< RequestType, ReplyType >::promise_type::reply.
operator bool()
template<typename RequestType , typename ReplyType > emlabcpp::coro::request_reply< RequestType, ReplyType >::operator bool () const inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done().
operator=() [1/2]
template<typename RequestType , typename ReplyType > request_reply& emlabcpp::coro::request_reply< RequestType, ReplyType >::operator= (const request_reply< RequestType, ReplyType > &) delete
operator=() [2/2]
template<typename RequestType , typename ReplyType > request_reply& emlabcpp::coro::request_reply< RequestType, ReplyType >::operator= (request_reply< RequestType, ReplyType > &&) default noexcept
store_reply()
template<typename RequestType , typename ReplyType > void emlabcpp::coro::request_reply< RequestType, ReplyType >::store_reply (const ReplyType & inpt) inline
References EMLABCPP_ERROR_LOG, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), and emlabcpp::coro::request_reply< RequestType, ReplyType >::promise_type::reply.
tick()
template<typename RequestType , typename ReplyType > bool emlabcpp::coro::request_reply< RequestType, ReplyType >::tick () inline
References emlabcpp::coro::request_reply< RequestType, ReplyType >::address(), emlabcpp::coro::owning_coroutine_handle< PromiseType >::done(), EMLABCPP_ERROR_LOG, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), emlabcpp::coro::request_reply< RequestType, ReplyType >::promise_type::reply, and emlabcpp::coro::request_reply< RequestType, ReplyType >::promise_type::request.
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/coro/request_reply.h