emlabcpp: emlabcpp::generic_iterator< Derived > Class Template Reference
emlabcpp::generic_iterator< Derived > Class Template Reference
generic_iterator simplifies custom iterator implementation using CRTP.
#include <iterator.h>
Public Types
using value_type = typename std::iterator_traits< Derived >::value_type
using reference = typename std::iterator_traits< Derived >::reference
using const_reference = reference const
using pointer = typename std::iterator_traits< Derived >::pointer
using const_pointer = typename std::iterator_traits< Derived >::const_pointer
using difference_type = typename std::iterator_traits< Derived >::difference_type
using iterator_category = typename std::iterator_traits< Derived >::iterator_category
Public Member Functions
constexpr pointer operator-> () noexcept(nothrow_dereference< Derived >)
constexpr const_pointer operator-> () const noexcept(nothrow_dereference< Derived >)
constexpr Derived & operator++ () noexcept(nothrow_add_assign< Derived >)
constexpr Derived operator++ (int const) noexcept(nothrow_add_assign< Derived > &&std::is_nothrow_copy_constructible_v< Derived >)
constexpr Derived & operator-- () noexcept(nothrow_sub_assign< Derived >)
constexpr Derived operator-- (int const) noexcept(nothrow_sub_assign< Derived > &&std::is_nothrow_copy_constructible_v< Derived >)
constexpr auto operator<=> (generic_iterator< Derived > const &other) const noexcept(nothrow_threeway_compare< Derived >)
constexpr bool operator== (generic_iterator< Derived > const &other) const noexcept(nothrow_equality_compare< Derived >)
constexpr Derived operator+ (difference_type v) const noexcept(nothrow_add_assign< Derived > &&std::is_nothrow_copy_constructible_v< Derived >)
constexpr Derived operator- (difference_type v) const noexcept(nothrow_sub_assign< Derived > &&std::is_nothrow_copy_constructible_v< Derived >)
Detailed Description
template<typename Derived>
class emlabcpp::generic_iterator< Derived >
generic_iterator simplifies custom iterator implementation using CRTP.
Users inherit from generic_iterator and pass their class as the Derived template argument. It relies on std::iterator_traits<Derived> for type definitions and provides additional methods based on those implemented in the Derived class.
The Derived class is expected to provide these methods:
reference operator*();
const_reference operator*() const;
Derived& operator+=(difference_type);
Derived& operator-=(difference_type);
bool operator<(const Derived & other);
bool operator==(const Derived & other);
difference_type operator-(const Derived& other);
Given these methods, the generic iterator provides:
pointer operator->();
const_pointer operator->() const;
Derived& operator++();
Derived operator++(int);
Derived& operator--();
Derived operator--(int);
Derived operator+(difference_type);
Derived operator-(difference_type);
Additionally, the following free functions are usable:
bool operator>(const generic_iterator<Derived> &, const generic_iterator<Derived>&);
bool operator<=(const generic_iterator<Derived> &, const generic_iterator<Derived>&);
bool operator!=(const generic_iterator<Derived> &, const generic_iterator<Derived>&);
Member Typedef Documentation
const_pointer
template<typename Derived > using emlabcpp::generic_iterator< Derived >::const_pointer = typename std::iterator_traits< Derived >::const_pointer
const_reference
template<typename Derived > using emlabcpp::generic_iterator< Derived >::const_reference = reference const
difference_type
template<typename Derived > using emlabcpp::generic_iterator< Derived >::difference_type = typename std::iterator_traits< Derived >::difference_type
iterator_category
template<typename Derived > using emlabcpp::generic_iterator< Derived >::iterator_category = typename std::iterator_traits< Derived >::iterator_category
pointer
template<typename Derived > using emlabcpp::generic_iterator< Derived >::pointer = typename std::iterator_traits< Derived >::pointer
reference
template<typename Derived > using emlabcpp::generic_iterator< Derived >::reference = typename std::iterator_traits< Derived >::reference
value_type
template<typename Derived > using emlabcpp::generic_iterator< Derived >::value_type = typename std::iterator_traits< Derived >::value_type
Member Function Documentation
operator+()
template<typename Derived > constexpr Derived emlabcpp::generic_iterator< Derived >::operator+ (difference_type v) const inline constexpr noexcept
References emlabcpp::copy().
operator++() [1/2]
template<typename Derived > constexpr Derived& emlabcpp::generic_iterator< Derived >::operator++ () inline constexpr noexcept
operator++() [2/2]
template<typename Derived > constexpr Derived emlabcpp::generic_iterator< Derived >::operator++ (int const) inline constexpr noexcept
References emlabcpp::copy().
operator-()
template<typename Derived > constexpr Derived emlabcpp::generic_iterator< Derived >::operator- (difference_type v) const inline constexpr noexcept
References emlabcpp::copy().
operator--() [1/2]
template<typename Derived > constexpr Derived& emlabcpp::generic_iterator< Derived >::operator-- () inline constexpr noexcept
operator--() [2/2]
template<typename Derived > constexpr Derived emlabcpp::generic_iterator< Derived >::operator-- (int const) inline constexpr noexcept
References emlabcpp::copy().
operator->() [1/2]
template<typename Derived > constexpr const_pointer emlabcpp::generic_iterator< Derived >::operator-> () const inline constexpr noexcept
operator->() [2/2]
template<typename Derived > constexpr pointer emlabcpp::generic_iterator< Derived >::operator-> () inline constexpr noexcept
operator<=>()
template<typename Derived > constexpr auto emlabcpp::generic_iterator< Derived >::operator<=> (generic_iterator< Derived > const & other) const inline constexpr noexcept
operator==()
template<typename Derived > constexpr bool emlabcpp::generic_iterator< Derived >::operator== (generic_iterator< Derived > const & other) const inline constexpr noexcept
The documentation for this class was generated from the following file:
include/emlabcpp/iterator.h