emlabcpp: emlabcpp::quaternion Class Reference
emlabcpp::quaternion Class Reference
API and behavior of this is inspired by tf::Quaternion.
#include <quaternion.h>
Public Types
using value_type = float
using const_iterator = typename container::const_iterator
using iterator = typename container::iterator
Public Member Functions
constexpr quaternion () noexcept=default
constexpr quaternion (float x, float y, float z, float w) noexcept
constexpr quaternion (const vector< 3 > &ax, const float &a) noexcept
constexpr float operator[] (std::size_t i) const noexcept
constexpr const_iterator begin () const
constexpr const_iterator end () const
constexpr iterator begin ()
constexpr iterator end ()
constexpr std::size_t size () const
Detailed Description
API and behavior of this is inspired by tf::Quaternion.
Member Typedef Documentation
const_iterator
using emlabcpp::quaternion::const_iterator = typename container::const_iterator
iterator
using emlabcpp::quaternion::iterator = typename container::iterator
value_type
using emlabcpp::quaternion::value_type = float
Constructor & Destructor Documentation
quaternion() [1/3]
constexpr emlabcpp::quaternion::quaternion () constexpr default noexcept
quaternion() [2/3]
constexpr emlabcpp::quaternion::quaternion (float x, float y, float z, float w) inline constexpr noexcept
quaternion() [3/3]
constexpr emlabcpp::quaternion::quaternion (const vector< 3 > & ax, const float & a) inline constexpr noexcept
References emlabcpp::cos(), emlabcpp::length_of(), and emlabcpp::sin().
Member Function Documentation
begin() [1/2]
constexpr iterator emlabcpp::quaternion::begin () inline constexpr
begin() [2/2]
constexpr const_iterator emlabcpp::quaternion::begin () const inline constexpr
end() [1/2]
constexpr iterator emlabcpp::quaternion::end () inline constexpr
end() [2/2]
constexpr const_iterator emlabcpp::quaternion::end () const inline constexpr
operator[]()
constexpr float emlabcpp::quaternion::operator[] (std::size_t i) const inline constexpr noexcept
size()
constexpr std::size_t emlabcpp::quaternion::size () const inline constexpr
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/geom/quaternion.h