emlabcpp: emlabcpp::testing::coroutine< T > Class Template Reference
emlabcpp::testing::coroutine< T > Class Template Reference
#include <coroutine.h>
Classes
struct promise_type
Public Types
using handle = std::coroutine_handle< promise_type >
using owning_handle = coro::owning_coroutine_handle< promise_type >
Public Member Functions
coroutine ()=default
coroutine (handle const &cor)
coroutine (coro_state s)
bool done () const
coro_state get_state () const override
bool await_ready () const
void await_suspend (auto const &h)
auto await_resume ()
auto run ()
void tick () override
Public Member Functions inherited from emlabcpp::testing::wait_interface
virtual ~wait_interface ()=default
Member Typedef Documentation
handle
template<typename T > using emlabcpp::testing::coroutine< T >::handle = std::coroutine_handle< promise_type >
owning_handle
template<typename T > using emlabcpp::testing::coroutine< T >::owning_handle = coro::owning_coroutine_handle< promise_type >
Constructor & Destructor Documentation
coroutine() [1/3]
template<typename T > emlabcpp::testing::coroutine< T >::coroutine () explicit default
coroutine() [2/3]
template<typename T > emlabcpp::testing::coroutine< T >::coroutine (handle const & cor) inline explicit
coroutine() [3/3]
template<typename T > emlabcpp::testing::coroutine< T >::coroutine (coro_state s) inline explicit
Member Function Documentation
await_ready()
template<typename T > bool emlabcpp::testing::coroutine< T >::await_ready () const inline
await_resume()
template<typename T > auto emlabcpp::testing::coroutine< T >::await_resume () inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), and emlabcpp::coro::data_promise< T >::value.
await_suspend()
template<typename T > void emlabcpp::testing::coroutine< T >::await_suspend (auto const & h) inline
done()
template<typename T > bool emlabcpp::testing::coroutine< T >::done () const inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done().
get_state()
template<typename T > coro_state emlabcpp::testing::coroutine< T >::get_state () const inline override virtual
Implements emlabcpp::testing::wait_interface.
run()
template<typename T > auto emlabcpp::testing::coroutine< T >::run () inline
References emlabcpp::testing::coroutine< T >::done(), emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), emlabcpp::testing::coroutine< T >::tick(), and emlabcpp::coro::data_promise< T >::value.
tick()
template<typename T > void emlabcpp::testing::coroutine< T >::tick () inline override virtual
Reimplemented from emlabcpp::testing::wait_interface.
References emlabcpp::testing::DONE, emlabcpp::testing::coroutine< T >::done(), emlabcpp::testing::ERRORED, emlabcpp::testing::FAILED, emlabcpp::testing::wait_interface::get_state(), emlabcpp::testing::coroutine< T >::promise_type::iface, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), emlabcpp::testing::SKIPPED, emlabcpp::testing::wait_interface::tick(), and emlabcpp::testing::WAITING.
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/coroutine.h