emlabcpp: emlabcpp::round_robin_executor< Coroutine, N > Class Template Reference
emlabcpp::round_robin_executor< Coroutine, N > Class Template Reference
#include <round_robin_executor.h>
Public Types
using container = static_vector< Coroutine, N >
using output_type = typename Coroutine::output_type
using input_type = typename Coroutine::input_type
Public Member Functions
bool register_coroutine (Coroutine cor)
bool empty () const
bool finished () const
Coroutine run (pool_interface *)
Member Typedef Documentation
container
template<typename Coroutine , std::size_t N> using emlabcpp::round_robin_executor< Coroutine, N >::container = static_vector< Coroutine, N >
input_type
template<typename Coroutine , std::size_t N> using emlabcpp::round_robin_executor< Coroutine, N >::input_type = typename Coroutine::input_type
output_type
template<typename Coroutine , std::size_t N> using emlabcpp::round_robin_executor< Coroutine, N >::output_type = typename Coroutine::output_type
Member Function Documentation
empty()
template<typename Coroutine , std::size_t N> bool emlabcpp::round_robin_executor< Coroutine, N >::empty () const inline
References emlabcpp::static_vector< T, N >::empty().
finished()
template<typename Coroutine , std::size_t N> bool emlabcpp::round_robin_executor< Coroutine, N >::finished () const inline
References emlabcpp::all_of().
register_coroutine()
template<typename Coroutine , std::size_t N> bool emlabcpp::round_robin_executor< Coroutine, N >::register_coroutine (Coroutine cor) inline
References emlabcpp::static_vector< T, N >::full(), and emlabcpp::static_vector< T, N >::push_back().
run()
template<typename Coroutine , std::size_t N> Coroutine emlabcpp::round_robin_executor< Coroutine, N >::run (pool_interface *) inline
References EMLABCPP_LOG, emlabcpp::round_robin_executor< Coroutine, N >::finished(), and emlabcpp::static_vector< T, N >::size().
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/coroutine/round_robin_executor.h