emlabcpp: emlabcpp::testing::test_coroutine Class Reference
emlabcpp::testing::test_coroutine Class Reference
#include <coroutine.h>
Classes
struct promise_type
Public Types
using handle = std::coroutine_handle< promise_type >
using owning_handle = coro::owning_coroutine_handle< promise_type >
Public Member Functions
test_coroutine ()=default
test_coroutine (const handle &cor)
bool done () const
await_state get_state () const override
bool await_ready () const
void await_suspend (const std::coroutine_handle< typename test_coroutine::promise_type > h)
void await_resume ()
void tick () override
Public Member Functions inherited from emlabcpp::testing::test_awaiter_interface
virtual ~test_awaiter_interface ()=default
Member Typedef Documentation
handle
using emlabcpp::testing::test_coroutine::handle = std::coroutine_handle< promise_type >
owning_handle
using emlabcpp::testing::test_coroutine::owning_handle = coro::owning_coroutine_handle< promise_type >
Constructor & Destructor Documentation
test_coroutine() [1/2]
emlabcpp::testing::test_coroutine::test_coroutine () default
test_coroutine() [2/2]
emlabcpp::testing::test_coroutine::test_coroutine (const handle & cor) inline explicit
Member Function Documentation
await_ready()
bool emlabcpp::testing::test_coroutine::await_ready () const inline
await_resume()
void emlabcpp::testing::test_coroutine::await_resume () inline
await_suspend()
void emlabcpp::testing::test_coroutine::await_suspend (const std::coroutine_handle< typename test_coroutine::promise_type > h) inline
done()
bool emlabcpp::testing::test_coroutine::done () const inline
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done().
get_state()
await_state emlabcpp::testing::test_coroutine::get_state () const inline override virtual
Implements emlabcpp::testing::test_awaiter_interface.
References done(), emlabcpp::testing::READY, and emlabcpp::testing::WAITING.
tick()
void emlabcpp::testing::test_coroutine::tick () inline override virtual
Reimplemented from emlabcpp::testing::test_awaiter_interface.
References emlabcpp::coro::owning_coroutine_handle< PromiseType >::done(), EMLABCPP_ERROR_LOG, emlabcpp::testing::ERRORED, emlabcpp::testing::test_awaiter_interface::get_state(), emlabcpp::testing::test_coroutine::promise_type::iface, emlabcpp::coro::owning_coroutine_handle< PromiseType >::promise(), emlabcpp::testing::test_awaiter_interface::tick(), and emlabcpp::testing::WAITING.
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/coroutine.h