emlabcpp: emlabcpp::decode_cobs_iter< Iter > Class Template Reference
emlabcpp::decode_cobs_iter< Iter > Class Template Reference
#include <cobs.h>
Public Member Functions
decode_cobs_iter (Iter iter)
std::byte operator* () const
decode_cobs_iter & operator++ ()
decode_cobs_iter operator++ (int)
bool operator== (decode_cobs_iter const &other) const
Public Member Functions inherited from emlabcpp::generic_iterator< decode_cobs_iter< Iter > >
constexpr pointer operator-> () noexcept(nothrow_dereference< decode_cobs_iter< Iter > >)
constexpr const_pointer operator-> () const noexcept(nothrow_dereference< decode_cobs_iter< Iter > >)
constexpr decode_cobs_iter< Iter > & operator++ () noexcept(nothrow_add_assign< decode_cobs_iter< Iter > >)
constexpr decode_cobs_iter< Iter > operator++ (int const) noexcept(nothrow_add_assign< decode_cobs_iter< Iter > > &&std::is_nothrow_copy_constructible_v< decode_cobs_iter< Iter > >)
constexpr decode_cobs_iter< Iter > & operator-- () noexcept(nothrow_sub_assign< decode_cobs_iter< Iter > >)
constexpr decode_cobs_iter< Iter > operator-- (int const) noexcept(nothrow_sub_assign< decode_cobs_iter< Iter > > &&std::is_nothrow_copy_constructible_v< decode_cobs_iter< Iter > >)
constexpr auto operator<=> (generic_iterator< decode_cobs_iter< Iter > > const &other) const noexcept(nothrow_threeway_compare< decode_cobs_iter< Iter > >)
constexpr bool operator== (generic_iterator< decode_cobs_iter< Iter > > const &other) const noexcept(nothrow_equality_compare< decode_cobs_iter< Iter > >)
constexpr decode_cobs_iter< Iter > operator+ (difference_type v) const noexcept(nothrow_add_assign< decode_cobs_iter< Iter > > &&std::is_nothrow_copy_constructible_v< decode_cobs_iter< Iter > >)
constexpr decode_cobs_iter< Iter > operator- (difference_type v) const noexcept(nothrow_sub_assign< decode_cobs_iter< Iter > > &&std::is_nothrow_copy_constructible_v< decode_cobs_iter< Iter > >)
Additional Inherited Members
Public Types inherited from emlabcpp::generic_iterator< decode_cobs_iter< Iter > >
using value_type = typename std::iterator_traits< decode_cobs_iter< Iter > >::value_type
using reference = typename std::iterator_traits< decode_cobs_iter< Iter > >::reference
using const_reference = reference const
using pointer = typename std::iterator_traits< decode_cobs_iter< Iter > >::pointer
using const_pointer = typename std::iterator_traits< decode_cobs_iter< Iter > >::const_pointer
using difference_type = typename std::iterator_traits< decode_cobs_iter< Iter > >::difference_type
using iterator_category = typename std::iterator_traits< decode_cobs_iter< Iter > >::iterator_category
Protected Member Functions inherited from emlabcpp::generic_iterator< decode_cobs_iter< Iter > >
generic_iterator () noexcept=default
Constructor & Destructor Documentation
decode_cobs_iter()
template<typename Iter > emlabcpp::decode_cobs_iter< Iter >::decode_cobs_iter (Iter iter) inline
Member Function Documentation
operator*()
template<typename Iter > std::byte emlabcpp::decode_cobs_iter< Iter >::operator* () const inline
References emlabcpp::cobs_decoder::get().
operator++() [1/2]
template<typename Iter > decode_cobs_iter& emlabcpp::decode_cobs_iter< Iter >::operator++ () inline
References emlabcpp::cobs_decoder::advance(), and emlabcpp::cobs_decoder::non_value_byte().
operator++() [2/2]
template<typename Iter > decode_cobs_iter emlabcpp::decode_cobs_iter< Iter >::operator++ (int) inline
References emlabcpp::res.
operator==()
template<typename Iter > bool emlabcpp::decode_cobs_iter< Iter >::operator== (decode_cobs_iter< Iter > const & other) const inline
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/cobs.h