emlabcpp: emlabcpp::protocol_sequencer< Def > Class Template Reference
emlabcpp::protocol_sequencer< Def > Class Template Reference
#include <sequencer.h>
Public Types
using message_type = typename Def::message_type
Public Member Functions
template<typename Iterator >
either< std::size_t, message_type > load_data (view< Iterator > dview)
Static Public Attributes
static constexpr auto prefix = Def::prefix
static constexpr std::size_t fixed_size = Def::fixed_size
Member Typedef Documentation
message_type
template<typename Def > using emlabcpp::protocol_sequencer< Def >::message_type = typename Def::message_type
Member Function Documentation
load_data()
template<typename Def > template<typename Iterator > either< std::size_t, message_type > emlabcpp::protocol_sequencer< Def >::load_data (view< Iterator > dview) inline
not match, remove one byte from buffer
partial match - more bytes could be matched
partial match - matched maximum bytes available
This is implied by the fact that we should have full match at the start of buffer
clean up only the matched message
References emlabcpp::static_circular_buffer< T, N >::begin(), emlabcpp::view< Iterator >::begin(), EMLABCPP_ASSERT, emlabcpp::static_circular_buffer< T, N >::empty(), emlabcpp::static_circular_buffer< T, N >::end(), emlabcpp::view< Iterator >::end(), emlabcpp::protocol_sequencer< Def >::fixed_size, emlabcpp::static_circular_buffer< T, N >::pop_front(), emlabcpp::protocol_sequencer< Def >::prefix, emlabcpp::static_circular_buffer< T, N >::size(), and emlabcpp::view_n().
Member Data Documentation
fixed_size
template<typename Def > constexpr std::size_t emlabcpp::protocol_sequencer< Def >::fixed_size = Def::fixed_size static constexpr
prefix
template<typename Def > constexpr auto emlabcpp::protocol_sequencer< Def >::prefix = Def::prefix static constexpr
The documentation for this class was generated from the following file:
include/emlabcpp/protocol/sequencer.h