emlabcpp: emlabcpp::testing::controller Class Reference
emlabcpp::testing::controller Class Reference
#include <controller.h>
Public Member Functions
std::string_view suite_name () const
std::string_view suite_date () const
bool has_active_test () const
const pool_map< test_id, test_info > & get_tests () const
void start_test (test_id tid, controller_interface &iface)
void tick (controller_interface &iface)
Static Public Member Functions
static std::optional< controller > make (controller_interface &iface, pool_interface *)
Member Function Documentation
get_tests()
const pool_map< test_id, test_info >& emlabcpp::testing::controller::get_tests () const inline
has_active_test()
bool emlabcpp::testing::controller::has_active_test () const inline
make()
static std::optional< controller > emlabcpp::testing::controller::make (controller_interface & iface, pool_interface *) static
start_test()
void emlabcpp::testing::controller::start_test (test_id tid, controller_interface & iface)
suite_date()
std::string_view emlabcpp::testing::controller::suite_date () const inline
References emlabcpp::static_vector< T, N >::begin(), and emlabcpp::static_vector< T, N >::end().
suite_name()
std::string_view emlabcpp::testing::controller::suite_name () const inline
References emlabcpp::static_vector< T, N >::begin(), and emlabcpp::static_vector< T, N >::end().
tick()
void emlabcpp::testing::controller::tick (controller_interface & iface)
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/controller.h