emlabcpp: emlabcpp::simplex< Item, N > Class Template Reference
emlabcpp::simplex< Item, N > Class Template Reference
#include <simplex.h>
Public Types
using container = std::array< Item, N+1 >
using value_type = Item
using iterator = typename container::iterator
using const_iterator = typename container::const_iterator
Public Member Functions
constexpr simplex ()=default
constexpr simplex (Item item)
constexpr simplex (const simplex< Item, N - 1 > &sub, Item item)
constexpr simplex (std::array< Item, N+1 > data)
template<typename... Ts>
constexpr simplex (Ts... ts)
constexpr const_iterator begin () const
constexpr const_iterator end () const
constexpr const Item & operator[] (std::size_t index) const
constexpr std::size_t size () const
Member Typedef Documentation
const_iterator
template<typename Item , std::size_t N> using emlabcpp::simplex< Item, N >::const_iterator = typename container::const_iterator
container
template<typename Item , std::size_t N> using emlabcpp::simplex< Item, N >::container = std::array< Item, N + 1 >
iterator
template<typename Item , std::size_t N> using emlabcpp::simplex< Item, N >::iterator = typename container::iterator
value_type
template<typename Item , std::size_t N> using emlabcpp::simplex< Item, N >::value_type = Item
Constructor & Destructor Documentation
simplex() [1/5]
template<typename Item , std::size_t N> constexpr emlabcpp::simplex< Item, N >::simplex () explicit constexpr default
simplex() [2/5]
template<typename Item , std::size_t N> constexpr emlabcpp::simplex< Item, N >::simplex (Item item) inline explicit constexpr
simplex() [3/5]
template<typename Item , std::size_t N> constexpr emlabcpp::simplex< Item, N >::simplex (const simplex< Item, N - 1 > & sub, Item item) inline constexpr
References emlabcpp::simplex< Item, N >::begin(), emlabcpp::copy(), and emlabcpp::simplex< Item, N >::end().
simplex() [4/5]
template<typename Item , std::size_t N> constexpr emlabcpp::simplex< Item, N >::simplex (std::array< Item, N+1 > data) inline constexpr
simplex() [5/5]
template<typename Item , std::size_t N> template<typename... Ts> constexpr emlabcpp::simplex< Item, N >::simplex (Ts... ts) inline explicit constexpr
Member Function Documentation
begin()
template<typename Item , std::size_t N> constexpr const_iterator emlabcpp::simplex< Item, N >::begin () const inline constexpr
end()
template<typename Item , std::size_t N> constexpr const_iterator emlabcpp::simplex< Item, N >::end () const inline constexpr
operator[]()
template<typename Item , std::size_t N> constexpr const Item& emlabcpp::simplex< Item, N >::operator[] (std::size_t index) const inline constexpr
size()
template<typename Item , std::size_t N> constexpr std::size_t emlabcpp::simplex< Item, N >::size () const inline constexpr
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/geom/simplex.h