emlabcpp: emlabcpp::pid< TimeType > Class Template Reference
emlabcpp::pid< TimeType > Class Template Reference
Implementation of PID regulator, the object should be constructed and populated with pid<T>::conf structure with configuration values (p,i,d coeficients, min/max output vals).
#include <pid.h>
Public Types
using time_type = TimeType
based on http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/
using config = pid_config
Public Member Functions
pid (time_type now, config conf=config{})
improvements from naive PID:
void set_time (time_type t)
void set_config (config conf)
const config & get_config () const
void set_pid (float p, float i, float d)
void set_pid (pid_coefficients c)
void set_limits (float min, float max)
void set_limits (min_max< float > lim)
const min_max< float > & get_limits () const
float update (time_type now, float measured, float desired)
call this reularly, the meaning of time value 'now' is up to you, just be consistent
void set_output (float output=0)
float get_output () const
float get_measured () const
float get_desired () const
Detailed Description
template<typename TimeType>
class emlabcpp::pid< TimeType >
Implementation of PID regulator, the object should be constructed and populated with pid<T>::conf structure with configuration values (p,i,d coeficients, min/max output vals).
The object contains all relevantstate data and should be called regularly.
Member Typedef Documentation
config
template<typename TimeType > using emlabcpp::pid< TimeType >::config = pid_config
time_type
template<typename TimeType > using emlabcpp::pid< TimeType >::time_type = TimeType
based on http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/
Constructor & Destructor Documentation
pid()
template<typename TimeType > emlabcpp::pid< TimeType >::pid (time_type now, config conf = config{}) inline
improvements from naive PID:
we work with derivation of measured, not error (error jumps in case you change desired value a lot)
we store i_term_ entirely (i * sum_) instead of just the sum_, makes it easier to change the scale of i (imagine what happens when you store sum_, use i*sum_ in the formula nad change i from 1 to 100)
Member Function Documentation
get_config()
template<typename TimeType > const config& emlabcpp::pid< TimeType >::get_config () const inline
get_desired()
template<typename TimeType > float emlabcpp::pid< TimeType >::get_desired () const inline
get_limits()
template<typename TimeType > const min_max< float >& emlabcpp::pid< TimeType >::get_limits () const inline
References emlabcpp::pid_config::limits.
get_measured()
template<typename TimeType > float emlabcpp::pid< TimeType >::get_measured () const inline
get_output()
template<typename TimeType > float emlabcpp::pid< TimeType >::get_output () const inline
set_config()
template<typename TimeType > void emlabcpp::pid< TimeType >::set_config (config conf) inline
References emlabcpp::pid_config::coefficients, emlabcpp::pid_config::limits, emlabcpp::pid< TimeType >::set_limits(), and emlabcpp::pid< TimeType >::set_pid().
set_limits() [1/2]
template<typename TimeType > void emlabcpp::pid< TimeType >::set_limits (float min, float max) inline
References emlabcpp::max(), and emlabcpp::min().
set_limits() [2/2]
template<typename TimeType > void emlabcpp::pid< TimeType >::set_limits (min_max< float > lim) inline
References emlabcpp::pid_config::limits, emlabcpp::min_max< T >::max, and emlabcpp::min_max< T >::min.
set_output()
template<typename TimeType > void emlabcpp::pid< TimeType >::set_output (float output = 0) inline
References emlabcpp::pid_config::limits, emlabcpp::min_max< T >::max, and emlabcpp::min_max< T >::min.
set_pid() [1/2]
template<typename TimeType > void emlabcpp::pid< TimeType >::set_pid (float p, float i, float d) inline
set_pid() [2/2]
template<typename TimeType > void emlabcpp::pid< TimeType >::set_pid (pid_coefficients c) inline
References emlabcpp::pid_config::coefficients.
set_time()
template<typename TimeType > void emlabcpp::pid< TimeType >::set_time (time_type t) inline
update()
template<typename TimeType > float emlabcpp::pid< TimeType >::update (time_type now, float measured, float desired) inline
call this reularly, the meaning of time value 'now' is up to you, just be consistent
Algorithm changes it's internal value output_ to the value that should be set to a 'thing' that controls measured_ value. It tries to control the 'thing' so the measured eventually converges to 'desired' value
we want to prevent the i_term_ to escallate out of proportion, to prevent it from going to infinity and beyond
References emlabcpp::pid_config::coefficients, emlabcpp::pid_coefficients::d, emlabcpp::pid_coefficients::i, emlabcpp::pid_config::limits, emlabcpp::min_max< T >::max, emlabcpp::min_max< T >::min, and emlabcpp::pid_coefficients::p.
The documentation for this class was generated from the following file:
include/emlabcpp/pid.h