emlabcpp: emlabcpp::static_vector< T, N > Class Template Reference
emlabcpp::static_vector< T, N > Class Template Reference
Data container for up to N elements.
#include <static_vector.h>
Public Types
using value_type = T
using size_type = std::size_t
using reference = T &
using const_reference = const T &
using iterator = T *
using const_iterator = const T *
Public Member Functions
static_vector ()=default
static_vector (const static_vector &other)
static_vector (static_vector &&other) noexcept
static_vector (std::size_t M, const T &item)
template<std::size_t M>
requires (M<=N) explicit static_vector(std
static_vector & operator= (const static_vector &other)
static_vector & operator= (static_vector &&other) noexcept
void swap (static_vector &other) noexcept
T * data ()
const T * data () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reference front ()
const_reference front () const
void push_back (T item)
template<typename... Args>
void emplace_back (Args &&... args)
T take_back ()
void pop_back ()
reference back ()
const_reference back () const
constexpr std::size_t max_size () const
other methods
std::size_t size () const
bool empty () const
bool full () const
const_reference operator[] (const size_type i) const
reference operator[] (const size_type i)
void clear ()
~static_vector ()
Static Public Attributes
static constexpr std::size_t capacity = N
Detailed Description
template<typename T, std::size_t N>
class emlabcpp::static_vector< T, N >
Data container for up to N elements.
Member Typedef Documentation
const_iterator
template<typename T , std::size_t N> using emlabcpp::static_vector< T, N >::const_iterator = const T*
const_reference
template<typename T , std::size_t N> using emlabcpp::static_vector< T, N >::const_reference = const T&
iterator
template<typename T , std::size_t N> using emlabcpp::static_vector< T, N >::iterator = T*
reference
template<typename T , std::size_t N> using emlabcpp::static_vector< T, N >::reference = T&
size_type
template<typename T , std::size_t N> using emlabcpp::static_vector< T, N >::size_type = std::size_t
value_type
template<typename T , std::size_t N> using emlabcpp::static_vector< T, N >::value_type = T
public types
Constructor & Destructor Documentation
static_vector() [1/4]
template<typename T , std::size_t N> emlabcpp::static_vector< T, N >::static_vector () default
public methods
static_vector() [2/4]
template<typename T , std::size_t N> emlabcpp::static_vector< T, N >::static_vector (const static_vector< T, N > & other) inline
static_vector() [3/4]
template<typename T , std::size_t N> emlabcpp::static_vector< T, N >::static_vector (static_vector< T, N > && other) inline noexcept
static_vector() [4/4]
template<typename T , std::size_t N> emlabcpp::static_vector< T, N >::static_vector (std::size_t M, const T & item) inline
References emlabcpp::static_vector< T, N >::begin(), and emlabcpp::max().
~static_vector()
template<typename T , std::size_t N> emlabcpp::static_vector< T, N >::~static_vector () inline
Member Function Documentation
back() [1/2]
template<typename T , std::size_t N> reference emlabcpp::static_vector< T, N >::back () inline
back() [2/2]
template<typename T , std::size_t N> const_reference emlabcpp::static_vector< T, N >::back () const inline
begin() [1/2]
template<typename T , std::size_t N> iterator emlabcpp::static_vector< T, N >::begin () inline
References emlabcpp::static_vector< T, N >::data().
begin() [2/2]
template<typename T , std::size_t N> const_iterator emlabcpp::static_vector< T, N >::begin () const inline
References emlabcpp::static_vector< T, N >::data().
clear()
template<typename T , std::size_t N> void emlabcpp::static_vector< T, N >::clear () inline
data() [1/2]
template<typename T , std::size_t N> T* emlabcpp::static_vector< T, N >::data () inline
data() [2/2]
template<typename T , std::size_t N> const T* emlabcpp::static_vector< T, N >::data () const inline
emplace_back()
template<typename T , std::size_t N> template<typename... Args> void emlabcpp::static_vector< T, N >::emplace_back (Args &&... args) inline
References emlabcpp::args.
empty()
template<typename T , std::size_t N> bool emlabcpp::static_vector< T, N >::empty () const inline
end() [1/2]
template<typename T , std::size_t N> iterator emlabcpp::static_vector< T, N >::end () inline
References emlabcpp::static_vector< T, N >::begin().
end() [2/2]
template<typename T , std::size_t N> const_iterator emlabcpp::static_vector< T, N >::end () const inline
References emlabcpp::static_vector< T, N >::begin().
front() [1/2]
template<typename T , std::size_t N> reference emlabcpp::static_vector< T, N >::front () inline
front() [2/2]
template<typename T , std::size_t N> const_reference emlabcpp::static_vector< T, N >::front () const inline
full()
template<typename T , std::size_t N> bool emlabcpp::static_vector< T, N >::full () const inline
max_size()
template<typename T , std::size_t N> constexpr std::size_t emlabcpp::static_vector< T, N >::max_size () const inline constexpr
other methods
operator=() [1/2]
template<typename T , std::size_t N> static_vector& emlabcpp::static_vector< T, N >::operator= (const static_vector< T, N > & other) inline
References emlabcpp::static_vector< T, N >::clear().
operator=() [2/2]
template<typename T , std::size_t N> static_vector& emlabcpp::static_vector< T, N >::operator= (static_vector< T, N > && other) inline noexcept
References emlabcpp::static_vector< T, N >::clear().
operator[]() [1/2]
template<typename T , std::size_t N> reference emlabcpp::static_vector< T, N >::operator[] (const size_type i) inline
operator[]() [2/2]
template<typename T , std::size_t N> const_reference emlabcpp::static_vector< T, N >::operator[] (const size_type i) const inline
pop_back()
template<typename T , std::size_t N> void emlabcpp::static_vector< T, N >::pop_back () inline
push_back()
template<typename T , std::size_t N> void emlabcpp::static_vector< T, N >::push_back (T item) inline
References emlabcpp::static_vector< T, N >::emplace_back().
requires()
template<typename T , std::size_t N> template<std::size_t M> emlabcpp::static_vector< T, N >::requires (M<= N) inline
References emlabcpp::static_vector< T, N >::data().
size()
template<typename T , std::size_t N> std::size_t emlabcpp::static_vector< T, N >::size () const inline
swap()
template<typename T , std::size_t N> void emlabcpp::static_vector< T, N >::swap (static_vector< T, N > & other) inline noexcept
References emlabcpp::static_vector< T, N >::emplace_back(), emlabcpp::min(), emlabcpp::static_vector< T, N >::pop_back(), emlabcpp::static_vector< T, N >::size(), and emlabcpp::swap().
take_back()
template<typename T , std::size_t N> T emlabcpp::static_vector< T, N >::take_back () inline
References emlabcpp::static_vector< T, N >::back(), and emlabcpp::static_vector< T, N >::pop_back().
Member Data Documentation
capacity
template<typename T , std::size_t N> constexpr std::size_t emlabcpp::static_vector< T, N >::capacity = N static constexpr
The documentation for this class was generated from the following file:
include/emlabcpp/static_vector.h