emlabcpp: emlabcpp::testing::executor Class Reference
emlabcpp::testing::executor Class Reference
#include <executor.h>
Public Member Functions
executor (run_id const rid, pmr::memory_resource &mem, test_interface &test)
test_status status () const
run_id get_run_id () const
void tick ()
bool finished () const
Constructor & Destructor Documentation
executor()
emlabcpp::testing::executor::executor (run_id const rid, pmr::memory_resource & mem, test_interface & test) inline
Member Function Documentation
finished()
bool emlabcpp::testing::executor::finished () const inline
get_run_id()
run_id emlabcpp::testing::executor::get_run_id () const inline
status()
test_status emlabcpp::testing::executor::status () const inline
tick()
void emlabcpp::testing::executor::tick () inline
References emlabcpp::testing::DONE, emlabcpp::testing::coroutine< T >::done(), emlabcpp::testing::ERRORED, emlabcpp::testing::coroutine< T >::get_state(), emlabcpp::testing::test_interface::run(), emlabcpp::testing::test_interface::setup(), emlabcpp::testing::test_interface::teardown(), and emlabcpp::testing::coroutine< T >::tick().
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/testing/executor.h