emlabcpp: emlabcpp::pretty_printer< StreamType > Class Template Reference
emlabcpp::pretty_printer< StreamType > Class Template Reference
#include <pretty_printer.h>
Public Member Functions
pretty_printer ()=default
pretty_printer (StreamType st)
template<typename T >
pretty_printer & operator<< (const T &item) &
operator bool () const
std::string str ()
char fill () const
char fill (char ch)
std::ios_base::fmtflags setf (std::ios_base::fmtflags flags, std::ios_base::fmtflags mask)
std::streamsize width () const
std::streamsize width (std::streamsize w)
std::ios_base::fmtflags flags () const
std::ios_base::fmtflags flags (std::ios_base::fmtflags f)
void main_print (const std::filesystem::path &p)
template<typename T >
void main_print (const std::reference_wrapper< T > &val)
template<std::same_as< uint8_t > T>
void main_print (const T &val)
template<typename T >
requires (detail::directly_streamable_for< std::ostream, T > &&!std::same_as< T, uint8_t > &&!std::is_enum_v< T >) void main_print(const T &val)
template<typename T >
requires (std::is_enum_v< T >) void main_print(const T &val)
void main_print (const char *c)
void main_print (const std::string_view &sview)
void main_print (const std::string &str)
template<typename... Ts>
void main_print (const std::variant< Ts... > &var)
template<typename... Ts>
void main_print (const std::tuple< Ts... > &tpl)
template<typename T >
void main_print (const std::optional< T > &val)
template<decomposable T>
void backup_print (const T &item)
Constructor & Destructor Documentation
pretty_printer() [1/2]
template<typename StreamType > emlabcpp::pretty_printer< StreamType >::pretty_printer () default
pretty_printer() [2/2]
template<typename StreamType > emlabcpp::pretty_printer< StreamType >::pretty_printer (StreamType st) inline
Member Function Documentation
backup_print()
template<typename StreamType > template<decomposable T> void emlabcpp::pretty_printer< StreamType >::backup_print (const T & item) inline
References emlabcpp::decompose().
fill() [1/2]
template<typename StreamType > char emlabcpp::pretty_printer< StreamType >::fill () const inline
fill() [2/2]
template<typename StreamType > char emlabcpp::pretty_printer< StreamType >::fill (char ch) inline
flags() [1/2]
template<typename StreamType > std::ios_base::fmtflags emlabcpp::pretty_printer< StreamType >::flags () const inline
flags() [2/2]
template<typename StreamType > std::ios_base::fmtflags emlabcpp::pretty_printer< StreamType >::flags (std::ios_base::fmtflags f) inline
References emlabcpp::f.
main_print() [1/9]
template<typename StreamType > void emlabcpp::pretty_printer< StreamType >::main_print (const char * c) inline
References emlabcpp::pretty_printer< StreamType >::main_print().
main_print() [2/9]
template<typename StreamType > void emlabcpp::pretty_printer< StreamType >::main_print (const std::filesystem::path & p) inline
main_print() [3/9]
template<typename StreamType > template<typename T > void emlabcpp::pretty_printer< StreamType >::main_print (const std::optional< T > & val) inline
main_print() [4/9]
template<typename StreamType > template<typename T > void emlabcpp::pretty_printer< StreamType >::main_print (const std::reference_wrapper< T > & val) inline
main_print() [5/9]
template<typename StreamType > void emlabcpp::pretty_printer< StreamType >::main_print (const std::string & str) inline
References emlabcpp::pretty_printer< StreamType >::str().
main_print() [6/9]
template<typename StreamType > void emlabcpp::pretty_printer< StreamType >::main_print (const std::string_view & sview) inline
main_print() [7/9]
template<typename StreamType > template<typename... Ts> void emlabcpp::pretty_printer< StreamType >::main_print (const std::tuple< Ts... > & tpl) inline
References emlabcpp::for_each().
main_print() [8/9]
template<typename StreamType > template<typename... Ts> void emlabcpp::pretty_printer< StreamType >::main_print (const std::variant< Ts... > & var) inline
References emlabcpp::visit().
main_print() [9/9]
template<typename StreamType > template<std::same_as< uint8_t > T> void emlabcpp::pretty_printer< StreamType >::main_print (const T & val) inline
operator bool()
template<typename StreamType > emlabcpp::pretty_printer< StreamType >::operator bool () const inline
operator<<()
template<typename StreamType > template<typename T > pretty_printer& emlabcpp::pretty_printer< StreamType >::operator<< (const T & item) & inline
References emlabcpp::pretty_printer< StreamType >::backup_print(), and emlabcpp::pretty_printer< StreamType >::main_print().
requires() [1/2]
template<typename StreamType > template<typename T > emlabcpp::pretty_printer< StreamType >::requires (detail::directly_streamable_for< std::ostream, T > &&!std::same_as< T, uint8_t > &&!std::is_enum_v< T >) const & inline
requires() [2/2]
template<typename StreamType > template<typename T > emlabcpp::pretty_printer< StreamType >::requires (std::is_enum_v< T >) const & inline
setf()
template<typename StreamType > std::ios_base::fmtflags emlabcpp::pretty_printer< StreamType >::setf (std::ios_base::fmtflags flags, std::ios_base::fmtflags mask) inline
References emlabcpp::pretty_printer< StreamType >::flags().
str()
template<typename StreamType > std::string emlabcpp::pretty_printer< StreamType >::str () inline
width() [1/2]
template<typename StreamType > std::streamsize emlabcpp::pretty_printer< StreamType >::width () const inline
width() [2/2]
template<typename StreamType > std::streamsize emlabcpp::pretty_printer< StreamType >::width (std::streamsize w) inline
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/pretty_printer.h