emlabcpp: emlabcpp::protocol::register_map< Endianess, Regs > Class Template Reference
emlabcpp::protocol::register_map< Endianess, Regs > Class Template Reference
Register map is abstraction to work with registers of external devices.
#include <register_map.h>
Public Types
using registers_tuple = std::tuple< Regs... >
using key_type = typename std::tuple_element_t< 0, registers_tuple >::key_type
using register_index = bounded< std::size_t, 0, registers_count - 1 >
using message_type = message< max_value_size >
template<key_type Key>
using reg_type = std::tuple_element_t< key_index< Key >, registers_tuple >
template<key_type Key>
using reg_value_type = typename reg_type< Key >::value_type
template<key_type Key>
using decl = typename reg_type< Key >::decl
template<key_type Key>
using reg_def_type = typename reg_type< Key >::def_type
Public Member Functions
register_map ()=default
register_map (typename Regs::value_type &... args)
constexpr bool contains (key_type key) const
template<key_type Key>
reg_value_type< Key > get_val () const
template<key_type Key>
void set_val (reg_value_type< Key > val)
template<typename UnaryCallable >
constexpr void setup_register (key_type key, UnaryCallable &&f)
template<typename UnaryCallable >
requires (!register_map_void_returning< UnaryCallable, registers_tuple >) const expr auto with_register(key_type key
with_register (key, [&res, &f](const auto &reg) { res=f(reg);})
template<typename UnaryCallable >
requires (register_map_void_returning< UnaryCallable, registers_tuple >) const expr void with_register(key_type key
Static Public Member Functions
static constexpr std::size_t register_size (register_index i)
static constexpr key_type register_key (register_index i)
Public Attributes
UnaryCallable &&f const
ret_type res
return res
Static Public Attributes
static constexpr std::endian endianess = Endianess
static constexpr std::size_t registers_count = sizeof...(Regs)
static constexpr std::size_t max_value_size = std::max({ Regs::decl::max_size... })
template<key_type Key>
static constexpr std::size_t key_index = get_reg_index(Key)
template<key_type Key>
static constexpr bool contains_key
Detailed Description
template<std::endian Endianess, typename... Regs>
class emlabcpp::protocol::register_map< Endianess, Regs >
Register map is abstraction to work with registers of external devices.
It stores values of serializable types that can be accessed based on key (usually enum representing address of register in the device).You can access the value based on the key itself, both at compile time and at runtime. You can also iterate over the values and there is handler that allows serialization and deserialization of bytes into the values defined in the map. This includes additional information that can be accessed about the map. This can also be used as simple table of configuration values.
Member Typedef Documentation
decl
template<std::endian Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::register_map< Endianess, Regs >::decl = typename reg_type< Key >::decl
key_type
template<std::endian Endianess, typename... Regs> using emlabcpp::protocol::register_map< Endianess, Regs >::key_type = typename std::tuple_element_t< 0, registers_tuple >::key_type
message_type
template<std::endian Endianess, typename... Regs> using emlabcpp::protocol::register_map< Endianess, Regs >::message_type = message< max_value_size >
reg_def_type
template<std::endian Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::register_map< Endianess, Regs >::reg_def_type = typename reg_type< Key >::def_type
reg_type
template<std::endian Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::register_map< Endianess, Regs >::reg_type = std::tuple_element_t< key_index< Key >, registers_tuple >
reg_value_type
template<std::endian Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::register_map< Endianess, Regs >::reg_value_type = typename reg_type< Key >::value_type
register_index
template<std::endian Endianess, typename... Regs> using emlabcpp::protocol::register_map< Endianess, Regs >::register_index = bounded< std::size_t, 0, registers_count - 1 >
registers_tuple
template<std::endian Endianess, typename... Regs> using emlabcpp::protocol::register_map< Endianess, Regs >::registers_tuple = std::tuple< Regs... >
Constructor & Destructor Documentation
register_map() [1/2]
template<std::endian Endianess, typename... Regs> emlabcpp::protocol::register_map< Endianess, Regs >::register_map () default
register_map() [2/2]
template<std::endian Endianess, typename... Regs> emlabcpp::protocol::register_map< Endianess, Regs >::register_map (typename Regs::value_type &... args) inline explicit
Member Function Documentation
contains()
template<std::endian Endianess, typename... Regs> constexpr bool emlabcpp::protocol::register_map< Endianess, Regs >::contains (key_type key) const inline constexpr
get_val()
template<std::endian Endianess, typename... Regs> template<key_type Key> reg_value_type< Key > emlabcpp::protocol::register_map< Endianess, Regs >::get_val () const inline
register_key()
template<std::endian Endianess, typename... Regs> static constexpr key_type emlabcpp::protocol::register_map< Endianess, Regs >::register_key (register_index i) inline static constexpr
References emlabcpp::select_index().
register_size()
template<std::endian Endianess, typename... Regs> static constexpr std::size_t emlabcpp::protocol::register_map< Endianess, Regs >::register_size (register_index i) inline static constexpr
References emlabcpp::select_index().
requires() [1/2]
template<std::endian Endianess, typename... Regs> template<typename UnaryCallable > emlabcpp::protocol::register_map< Endianess, Regs >::requires (!register_map_void_returning< UnaryCallable, registers_tuple >) const
requires() [2/2]
template<std::endian Endianess, typename... Regs> template<typename UnaryCallable > emlabcpp::protocol::register_map< Endianess, Regs >::requires (register_map_void_returning< UnaryCallable, registers_tuple >) const
References emlabcpp::f.
set_val()
template<std::endian Endianess, typename... Regs> template<key_type Key> void emlabcpp::protocol::register_map< Endianess, Regs >::set_val (reg_value_type< Key > val) inline
setup_register()
template<std::endian Endianess, typename... Regs> template<typename UnaryCallable > constexpr void emlabcpp::protocol::register_map< Endianess, Regs >::setup_register (key_type key, UnaryCallable && f) inline constexpr
References emlabcpp::f, and emlabcpp::protocol::register_map< Endianess, Regs >::with_register().
with_register()
template<std::endian Endianess, typename... Regs> emlabcpp::protocol::register_map< Endianess, Regs >::with_register (key , [&res, &f] (const auto &reg) { res=f(reg);})
References emlabcpp::f, and emlabcpp::protocol::register_map< Endianess, Regs >::res.
Member Data Documentation
const
template<std::endian Endianess, typename... Regs> UnaryCallable &&f emlabcpp::protocol::register_map< Endianess, Regs >::const
Initial value:
{
                using ret_type = decltype( f( std::get< 0 >( registers_ ) ) )
contains_key
template<std::endian Endianess, typename... Regs> template<key_type Key> constexpr bool emlabcpp::protocol::register_map< Endianess, Regs >::contains_key static constexpr
Initial value:
=
            key_index< Key > != std::tuple_size_v< registers_tuple >
endianess
template<std::endian Endianess, typename... Regs> constexpr std::endian emlabcpp::protocol::register_map< Endianess, Regs >::endianess = Endianess static constexpr
key_index
template<std::endian Endianess, typename... Regs> template<key_type Key> constexpr std::size_t emlabcpp::protocol::register_map< Endianess, Regs >::key_index = get_reg_index(Key) static constexpr
max_value_size
template<std::endian Endianess, typename... Regs> constexpr std::size_t emlabcpp::protocol::register_map< Endianess, Regs >::max_value_size = std::max({ Regs::decl::max_size... }) static constexpr
registers_count
template<std::endian Endianess, typename... Regs> constexpr std::size_t emlabcpp::protocol::register_map< Endianess, Regs >::registers_count = sizeof...(Regs) static constexpr
res [1/2]
template<std::endian Endianess, typename... Regs> ret_type emlabcpp::protocol::register_map< Endianess, Regs >::res
res [2/2]
template<std::endian Endianess, typename... Regs> return emlabcpp::protocol::register_map< Endianess, Regs >::res
The documentation for this class was generated from the following file:
include/emlabcpp/protocol/register_map.h