emlabcpp: emlabcpp::rpc::reactor< CallDefs > Class Template Reference
emlabcpp::rpc::reactor< CallDefs > Class Template Reference
#include <rpc.h>
Public Types
using traits_type = traits< CallDefs >
using reply_variant = typename traits_type::reply_variant
using request_type = typename traits_type::request_type
using request_group = typename traits_type::request_group
using reply_type = typename traits_type::reply_type
using outter_reply_group = typename traits_type::outter_reply_group
using request_message_type = typename traits_type::request_message_type
using reply_message_type = typename traits_type::reply_message_type
using request_handler = protocol::handler< request_group >
using reply_handler = protocol::handler< outter_reply_group >
Static Public Member Functions
template<typename Handler >
static reply_message_type on_message (const request_message_type &msg, Handler &&h)
Member Typedef Documentation
outter_reply_group
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::outter_reply_group = typename traits_type::outter_reply_group
reply_handler
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::reply_handler = protocol::handler< outter_reply_group >
reply_message_type
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::reply_message_type = typename traits_type::reply_message_type
reply_type
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::reply_type = typename traits_type::reply_type
reply_variant
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::reply_variant = typename traits_type::reply_variant
request_group
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::request_group = typename traits_type::request_group
request_handler
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::request_handler = protocol::handler< request_group >
request_message_type
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::request_message_type = typename traits_type::request_message_type
request_type
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::request_type = typename traits_type::request_type
traits_type
template<typename CallDefs > using emlabcpp::rpc::reactor< CallDefs >::traits_type = traits< CallDefs >
Member Function Documentation
on_message()
template<typename CallDefs > template<typename Handler > static reply_message_type emlabcpp::rpc::reactor< CallDefs >::on_message (const request_message_type & msg, Handler && h) inline static
References EMLABCPP_ERROR_LOG, emlabcpp::protocol::handler< T >::extract(), emlabcpp::protocol::handler< T >::serialize(), and emlabcpp::visit_index().
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/rpc.h