emlabcpp: emlabcpp::protocol::protocol_register_map< Endianess, Regs > Class Template Reference
emlabcpp::protocol::protocol_register_map< Endianess, Regs > Class Template Reference
Register map is abstraction to work with registers of external devices.
#include <register_map.h>
Public Types
using registers_tuple = std::tuple< Regs... >
using key_type = typename std::tuple_element_t< 0, registers_tuple >::key_type
using register_index = bounded< std::size_t, 0, registers_count - 1 >
using message_type = message< max_value_size >
template<key_type Key>
using reg_type = std::tuple_element_t< key_index< Key >, registers_tuple >
template<key_type Key>
using reg_value_type = typename reg_type< Key >::value_type
template<key_type Key>
using decl = typename reg_type< Key >::decl
template<key_type Key>
using reg_def_type = typename reg_type< Key >::def_type
Public Member Functions
protocol_register_map ()=default
protocol_register_map (typename Regs::value_type... args)
constexpr bool contains (key_type key) const
template<key_type Key>
reg_value_type< Key > get_val () const
template<key_type Key>
void set_val (reg_value_type< Key > val)
template<typename UnaryCallable >
constexpr void setup_register (key_type key, UnaryCallable &&f)
template<typename UnaryCallable >
requires (!protocol_register_map_void_returning< UnaryCallable, registers_tuple >) const expr auto with_register(key_type key
with_register (key, [&](const auto &reg) { res=f(reg);})
template<typename UnaryCallable >
requires (protocol_register_map_void_returning< UnaryCallable, registers_tuple >) const expr void with_register(key_type key
Static Public Member Functions
static constexpr std::size_t register_size (register_index i)
static constexpr key_type register_key (register_index i)
Public Attributes
UnaryCallable &&f const
ret_type res
return res
Static Public Attributes
static constexpr endianess_enum endianess = Endianess
static constexpr std::size_t registers_count = sizeof...(Regs)
static constexpr std::size_t max_value_size = std::max({ Regs::decl::max_size... })
template<key_type Key>
static constexpr std::size_t key_index = get_reg_index(Key)
template<key_type Key>
static constexpr bool contains_key
Detailed Description
template<endianess_enum Endianess, typename... Regs>
class emlabcpp::protocol::protocol_register_map< Endianess, Regs >
Register map is abstraction to work with registers of external devices.
It stores values of serializable types that can be accessed based on key (usually enum representing address of register in the device).You can access the value based on the key itself, both at compile time and at runtime. You can also iterate over the values and there is handler that allows serialization and deserialization of bytes into the values defined in the map. This includes additional information that can be accessed about the map. This can also be used as simple table of configuration values.
Member Typedef Documentation
decl
template<endianess_enum Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::decl = typename reg_type< Key >::decl
key_type
template<endianess_enum Endianess, typename... Regs> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::key_type = typename std::tuple_element_t< 0, registers_tuple >::key_type
message_type
template<endianess_enum Endianess, typename... Regs> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::message_type = message< max_value_size >
reg_def_type
template<endianess_enum Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::reg_def_type = typename reg_type< Key >::def_type
reg_type
template<endianess_enum Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::reg_type = std::tuple_element_t< key_index< Key >, registers_tuple >
reg_value_type
template<endianess_enum Endianess, typename... Regs> template<key_type Key> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::reg_value_type = typename reg_type< Key >::value_type
register_index
template<endianess_enum Endianess, typename... Regs> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::register_index = bounded< std::size_t, 0, registers_count - 1 >
registers_tuple
template<endianess_enum Endianess, typename... Regs> using emlabcpp::protocol::protocol_register_map< Endianess, Regs >::registers_tuple = std::tuple< Regs... >
Constructor & Destructor Documentation
protocol_register_map() [1/2]
template<endianess_enum Endianess, typename... Regs> emlabcpp::protocol::protocol_register_map< Endianess, Regs >::protocol_register_map () default
protocol_register_map() [2/2]
template<endianess_enum Endianess, typename... Regs> emlabcpp::protocol::protocol_register_map< Endianess, Regs >::protocol_register_map (typename Regs::value_type... args) inline
Member Function Documentation
contains()
template<endianess_enum Endianess, typename... Regs> constexpr bool emlabcpp::protocol::protocol_register_map< Endianess, Regs >::contains (key_type key) const inline constexpr
get_val()
template<endianess_enum Endianess, typename... Regs> template<key_type Key> reg_value_type< Key > emlabcpp::protocol::protocol_register_map< Endianess, Regs >::get_val () const inline
register_key()
template<endianess_enum Endianess, typename... Regs> static constexpr key_type emlabcpp::protocol::protocol_register_map< Endianess, Regs >::register_key (register_index i) inline static constexpr
References emlabcpp::select_index().
register_size()
template<endianess_enum Endianess, typename... Regs> static constexpr std::size_t emlabcpp::protocol::protocol_register_map< Endianess, Regs >::register_size (register_index i) inline static constexpr
References emlabcpp::select_index().
requires() [1/2]
template<endianess_enum Endianess, typename... Regs> template<typename UnaryCallable > emlabcpp::protocol::protocol_register_map< Endianess, Regs >::requires (!protocol_register_map_void_returning< UnaryCallable, registers_tuple >) const
requires() [2/2]
template<endianess_enum Endianess, typename... Regs> template<typename UnaryCallable > emlabcpp::protocol::protocol_register_map< Endianess, Regs >::requires (protocol_register_map_void_returning< UnaryCallable, registers_tuple >) const
References emlabcpp::f.
set_val()
template<endianess_enum Endianess, typename... Regs> template<key_type Key> void emlabcpp::protocol::protocol_register_map< Endianess, Regs >::set_val (reg_value_type< Key > val) inline
setup_register()
template<endianess_enum Endianess, typename... Regs> template<typename UnaryCallable > constexpr void emlabcpp::protocol::protocol_register_map< Endianess, Regs >::setup_register (key_type key, UnaryCallable && f) inline constexpr
References emlabcpp::f, and emlabcpp::protocol::protocol_register_map< Endianess, Regs >::with_register().
with_register()
template<endianess_enum Endianess, typename... Regs> emlabcpp::protocol::protocol_register_map< Endianess, Regs >::with_register (key , [&] (const auto &reg) { res=f(reg);})
References emlabcpp::f, and emlabcpp::protocol::protocol_register_map< Endianess, Regs >::res.
Member Data Documentation
const
template<endianess_enum Endianess, typename... Regs> UnaryCallable &&f emlabcpp::protocol::protocol_register_map< Endianess, Regs >::const
Initial value:
{
                using ret_type = decltype( f( std::get< 0 >( registers_ ) ) )
contains_key
template<endianess_enum Endianess, typename... Regs> template<key_type Key> constexpr bool emlabcpp::protocol::protocol_register_map< Endianess, Regs >::contains_key static constexpr
Initial value:
=
            key_index< Key > != std::tuple_size_v< registers_tuple >
endianess
template<endianess_enum Endianess, typename... Regs> constexpr endianess_enum emlabcpp::protocol::protocol_register_map< Endianess, Regs >::endianess = Endianess static constexpr
key_index
template<endianess_enum Endianess, typename... Regs> template<key_type Key> constexpr std::size_t emlabcpp::protocol::protocol_register_map< Endianess, Regs >::key_index = get_reg_index(Key) static constexpr
max_value_size
template<endianess_enum Endianess, typename... Regs> constexpr std::size_t emlabcpp::protocol::protocol_register_map< Endianess, Regs >::max_value_size = std::max({ Regs::decl::max_size... }) static constexpr
registers_count
template<endianess_enum Endianess, typename... Regs> constexpr std::size_t emlabcpp::protocol::protocol_register_map< Endianess, Regs >::registers_count = sizeof...(Regs) static constexpr
res [1/2]
template<endianess_enum Endianess, typename... Regs> ret_type emlabcpp::protocol::protocol_register_map< Endianess, Regs >::res
res [2/2]
template<endianess_enum Endianess, typename... Regs> return emlabcpp::protocol::protocol_register_map< Endianess, Regs >::res
The documentation for this class was generated from the following file:
include/emlabcpp/protocol/register_map.h