emlabcpp: emlabcpp::noneabi_logger Class Reference
emlabcpp::noneabi_logger Class Reference
#include <noneabi_logger.h>
Public Member Functions
template<typename... Args>
void log (const Args &... args)
template<typename T >
void write (const T &t)
void write (std::string_view data)
void end ()
Member Function Documentation
end()
void emlabcpp::noneabi_logger::end () inline
References emlabcpp::noneabi_log_end().
log()
template<typename... Args> void emlabcpp::noneabi_logger::log (const Args &... args) inline
References emlabcpp::args, end(), and write().
write() [1/2]
template<typename T > void emlabcpp::noneabi_logger::write (const T & t) inline
write() [2/2]
void emlabcpp::noneabi_logger::write (std::string_view data) inline
References emlabcpp::noneabi_log_write().
The documentation for this class was generated from the following file:
include/emlabcpp/experimental/logging/noneabi_logger.h