emlabcpp: emlabcpp::cfg Namespace Reference
emlabcpp::cfg Namespace Reference
MIT License.
Classes
struct deser_res
struct iface_base
struct update_iface
struct update_cbs
struct update_cbs_bind
struct load_iface
struct load_cbs
struct load_cbs_bind
struct activ_page_sel
Typedefs
using cell = uint64_t
template<typename T >
using opt = std::optional< T >
Enumerations
enum class ser_res : uint8_t {
SINGLE ,
MULTI
}
enum class cache_res {
SEEN ,
NOT_SEEN
}
enum class update_result : uint8_t {
SUCCESS = 0x00 ,
ERROR = 0x01 ,
FULL = 0x02
}
enum class hdr_state : uint8_t {
A = 0x40 ,
B = A + 0x40 ,
C = B + 0x40
}
Functions
constexpr uint32_t closest_multiple_of (uint32_t x, uint32_t r) noexcept
opt< ser_res > ser_cell (uint32_t key, std::span< std::byte > value, std::span< std::byte, cell_size > dest)
opt< deser_res > deser_cell (std::span< std::byte, cell_size > c)
opt< std::span< std::byte > > store_kval_impl (uint32_t key, std::byte *beg, std::byte *val_end, std::byte *end)
template<typename T >
opt< std::span< std::byte > > store_kval (uint32_t key, T const &val, std::span< std::byte > buffer)
template<typename T >
opt< T > get_val (std::span< std::byte > data)
bool is_free_cell (std::span< std::byte, cell_size > cell)
opt< uint16_t > locate_current_page (std::size_t mem_size, std::size_t page_size, iface_base &iface)
opt< std::pair< std::size_t, hdr_state > > locate_next_page (std::size_t mem_size, std::size_t page_size, iface_base &iface)
std::span< std::byte > manifest_value (bool is_seq, auto &cell_val, auto &decr_addr, auto &addr, auto &iface, auto &buffer)
update_result store_key (std::size_t &addr, uint32_t key, update_iface &iface)
update_result dump_unseen_keys (std::size_t addr, update_iface &iface)
update_result update_stored_config (std::size_t start_addr, std::size_t end_addr, update_iface &iface)
result update (std::size_t mem_size, std::size_t page_size, update_iface &iface)
result load_stored_config (std::size_t start_addr, std::size_t end_addr, load_iface &iface)
result load (std::size_t mem_size, std::size_t page_size, load_iface &iface)
opt< std::size_t > pop_from_container (auto &cont)
cache_res key_check_unseen_container (auto &cont, uint32_t key)
template<typename M >
opt< std::size_t > serialize_reg_map_key (M &reg_map, uint32_t key, std::span< std::byte > buffer)
template<typename M >
result set_reg_map_key (M &reg_map, uint32_t key, std::span< std::byte > buffer)
template<typename M >
bool reg_map_value_changed (M &reg_map, uint32_t key, std::span< std::byte > data)
hdr_state next (hdr_state cs) noexcept
opt< hdr_state > byte_to_hdr (std::byte b) noexcept
std::array< std::byte, 2 > get_hdr (hdr_state hst) noexcept
Variables
static constexpr uint16_t cell_size = sizeof(cell)
static constexpr uint16_t hcell_size = sizeof(cell) / 2
static constexpr uint32_t key_mask = 0x7FFFFFFF
static constexpr uint32_t sin_bit_mask = 0x80000000
Detailed Description
MIT License.
Copyright (c) 2025 Jan Veverak Koniarik
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Class Documentation
emlabcpp::cfg::deser_res
struct emlabcpp::cfg::deser_res
Class Members
bool is_seq
uint32_t key
uint32_t val
emlabcpp::cfg::update_cbs
struct emlabcpp::cfg::update_cbs
template<typename Read, typename Write, typename KeyCheck, typename ValueChanged, typename SerializeKey, typename TakeUnseenKey, typename ResetKeys>
struct emlabcpp::cfg::update_cbs< Read, Write, KeyCheck, ValueChanged, SerializeKey, TakeUnseenKey, ResetKeys >
Class Members
span< byte > buffer
KeyCheck check_key_cache_f
Read read_f
ResetKeys reset_keys_f
SerializeKey serialize_key_f
TakeUnseenKey take_unseen_key_f
ValueChanged value_changed_f
Write write_f
emlabcpp::cfg::load_cbs
struct emlabcpp::cfg::load_cbs
template<typename Read, typename KeyCheck, typename OnKval>
struct emlabcpp::cfg::load_cbs< Read, KeyCheck, OnKval >
Class Members
span< byte > buffer
KeyCheck check_key_cache_f
OnKval on_kval_f
Read read_f
Typedef Documentation
cell
using emlabcpp::cfg::cell = typedef uint64_t
opt
template<typename T > using emlabcpp::cfg::opt = typedef std::optional< T >
Enumeration Type Documentation
cache_res
enum emlabcpp::cfg::cache_res strong
Enumerator
SEEN
NOT_SEEN
hdr_state
enum emlabcpp::cfg::hdr_state : uint8_t strong
Enumerator
A
B
C
ser_res
enum emlabcpp::cfg::ser_res : uint8_t strong
Enumerator
SINGLE
MULTI
update_result
enum emlabcpp::cfg::update_result : uint8_t strong
Enumerator
SUCCESS
ERROR
FULL
Function Documentation
byte_to_hdr()
opt< hdr_state > emlabcpp::cfg::byte_to_hdr (std::byte b) inline noexcept
References A, B, and C.
closest_multiple_of()
constexpr uint32_t emlabcpp::cfg::closest_multiple_of (uint32_t x, uint32_t r) constexpr noexcept
deser_cell()
opt< deser_res > emlabcpp::cfg::deser_cell (std::span< std::byte, cell_size > c) inline
References emlabcpp::cfg::deser_res::is_seq, key_mask, and sin_bit_mask.
dump_unseen_keys()
update_result emlabcpp::cfg::dump_unseen_keys (std::size_t addr, update_iface & iface) inline
References emlabcpp::res, store_key(), SUCCESS, and emlabcpp::cfg::update_iface::take_unseen_key().
get_hdr()
std::array< std::byte, 2 > emlabcpp::cfg::get_hdr (hdr_state hst) inline noexcept
get_val()
template<typename T > opt< T > emlabcpp::cfg::get_val (std::span< std::byte > data)
References emlabcpp::data(), emlabcpp::protocol::deserialize(), and emlabcpp::res.
is_free_cell()
bool emlabcpp::cfg::is_free_cell (std::span< std::byte, cell_size > cell) inline
References emlabcpp::all_of().
key_check_unseen_container()
cache_res emlabcpp::cfg::key_check_unseen_container (auto & cont, uint32_t key)
References emlabcpp::find(), NOT_SEEN, SEEN, and emlabcpp::swap().
load()
result emlabcpp::cfg::load (std::size_t mem_size, std::size_t page_size, load_iface & iface) inline
References cell_size, load_stored_config(), and locate_current_page().
load_stored_config()
result emlabcpp::cfg::load_stored_config (std::size_t start_addr, std::size_t end_addr, load_iface & iface) inline
References cell_size, emlabcpp::cfg::load_iface::check_key_cache(), deser_cell(), emlabcpp::cfg::iface_base::get_buffer(), manifest_value(), emlabcpp::cfg::load_iface::on_kval(), emlabcpp::cfg::iface_base::read(), and SEEN.
locate_current_page()
opt< uint16_t > emlabcpp::cfg::locate_current_page (std::size_t mem_size, std::size_t page_size, iface_base & iface) inline
References cell_size, emlabcpp::data(), emlabcpp::cfg::activ_page_sel::hdr_st, emlabcpp::cfg::activ_page_sel::idx, emlabcpp::cfg::activ_page_sel::on_raw_hdr(), and emlabcpp::cfg::iface_base::read().
locate_next_page()
opt< std::pair< std::size_t, hdr_state > > emlabcpp::cfg::locate_next_page (std::size_t mem_size, std::size_t page_size, iface_base & iface) inline
References A, cell_size, emlabcpp::data(), emlabcpp::cfg::activ_page_sel::hdr_st, emlabcpp::cfg::activ_page_sel::idx, emlabcpp::cfg::activ_page_sel::on_raw_hdr(), and emlabcpp::cfg::iface_base::read().
manifest_value()
std::span< std::byte > emlabcpp::cfg::manifest_value (bool is_seq, auto & cell_val, auto & decr_addr, auto & addr, auto & iface, auto & buffer)
References cell_size.
next()
hdr_state emlabcpp::cfg::next (hdr_state cs) inline noexcept
References A, B, and C.
pop_from_container()
opt< std::size_t > emlabcpp::cfg::pop_from_container (auto & cont)
reg_map_value_changed()
template<typename M > bool emlabcpp::cfg::reg_map_value_changed (M & reg_map, uint32_t key, std::span< std::byte > data)
References emlabcpp::data(), and emlabcpp::res.
ser_cell()
opt< ser_res > emlabcpp::cfg::ser_cell (uint32_t key, std::span< std::byte > value, std::span< std::byte, cell_size > dest) inline
References cell_size, closest_multiple_of(), hcell_size, MULTI, sin_bit_mask, and SINGLE.
serialize_reg_map_key()
template<typename M > opt< std::size_t > emlabcpp::cfg::serialize_reg_map_key (M & reg_map, uint32_t key, std::span< std::byte > buffer)
References emlabcpp::res, and store_kval().
set_reg_map_key()
template<typename M > result emlabcpp::cfg::set_reg_map_key (M & reg_map, uint32_t key, std::span< std::byte > buffer)
References emlabcpp::res.
store_key()
update_result emlabcpp::cfg::store_key (std::size_t & addr, uint32_t key, update_iface & iface)
References ERROR, FULL, emlabcpp::cfg::iface_base::get_buffer(), emlabcpp::cfg::update_iface::serialize_key(), SUCCESS, and emlabcpp::cfg::update_iface::write().
store_kval()
template<typename T > opt< std::span< std::byte > > emlabcpp::cfg::store_kval (uint32_t key, T const & val, std::span< std::byte > buffer)
References emlabcpp::protocol::max_size, emlabcpp::protocol::serialize_at(), and store_kval_impl().
store_kval_impl()
opt< std::span< std::byte > > emlabcpp::cfg::store_kval_impl (uint32_t key, std::byte * beg, std::byte * val_end, std::byte * end) inline
References cell_size, MULTI, ser_cell(), and SINGLE.
update()
result emlabcpp::cfg::update (std::size_t mem_size, std::size_t page_size, update_iface & iface) inline
References cell_size, dump_unseen_keys(), FULL, get_hdr(), locate_current_page(), locate_next_page(), emlabcpp::cfg::update_iface::reset_keys(), SUCCESS, update_stored_config(), and emlabcpp::cfg::update_iface::write().
update_stored_config()
update_result emlabcpp::cfg::update_stored_config (std::size_t start_addr, std::size_t end_addr, update_iface & iface) inline
References cell_size, emlabcpp::cfg::update_iface::check_key_cache(), deser_cell(), dump_unseen_keys(), ERROR, emlabcpp::cfg::iface_base::get_buffer(), is_free_cell(), manifest_value(), emlabcpp::cfg::iface_base::read(), emlabcpp::res, SEEN, store_key(), SUCCESS, and emlabcpp::cfg::update_iface::value_changed().
Variable Documentation
cell_size
constexpr uint16_t emlabcpp::cfg::cell_size = sizeof(cell) static constexpr
hcell_size
constexpr uint16_t emlabcpp::cfg::hcell_size = sizeof(cell) / 2 static constexpr
key_mask
constexpr uint32_t emlabcpp::cfg::key_mask = 0x7FFFFFFF static constexpr
sin_bit_mask
constexpr uint32_t emlabcpp::cfg::sin_bit_mask = 0x80000000 static constexpr