emlabcpp: emlabcpp::protocol::packet_handler< Packet > Struct Template Reference
emlabcpp::protocol::packet_handler< Packet > Struct Template Reference
#include <packet_handler.h>
Public Types
using message_type = typename Packet::message_type
using prefix_type = typename Packet::prefix_type
using payload_type = typename Packet::payload_type
using value_type = typename Packet::value_type
using size_type = typename Packet::size_type
using checksum_type = typename Packet::checksum_type
using sub_handler = handler< Packet >
Static Public Member Functions
static message_type serialize (const value_type &val)
static either< value_type, error_record > extract (const view< const std::byte * > &msg)
Static Public Attributes
static constexpr std::size_t size_offset = Packet::prefix_traits::max_size
static constexpr std::size_t checksum_size = Packet::checksum_traits::max_size
static constexpr std::size_t size_size = Packet::size_traits::max_size
static constexpr auto endianess = Packet::endianess
Member Typedef Documentation
checksum_type
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::checksum_type = typename Packet::checksum_type
message_type
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::message_type = typename Packet::message_type
payload_type
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::payload_type = typename Packet::payload_type
prefix_type
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::prefix_type = typename Packet::prefix_type
size_type
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::size_type = typename Packet::size_type
sub_handler
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::sub_handler = handler< Packet >
value_type
template<typename Packet > using emlabcpp::protocol::packet_handler< Packet >::value_type = typename Packet::value_type
Member Function Documentation
extract()
template<typename Packet > static either< value_type, error_record > emlabcpp::protocol::packet_handler< Packet >::extract (const view< const std::byte * > & msg) inline static
References emlabcpp::view< Iterator, EndIterator >::begin(), emlabcpp::protocol::CHECKSUM_ERR, emlabcpp::protocol::packet_handler< Packet >::checksum_size, EMLABCPP_ERROR_LOG, emlabcpp::protocol::handler< T >::extract(), emlabcpp::view< Iterator, EndIterator >::size(), and emlabcpp::view_n().
serialize()
template<typename Packet > static message_type emlabcpp::protocol::packet_handler< Packet >::serialize (const value_type & val) inline static
References emlabcpp::protocol::packet_handler< Packet >::checksum_size, emlabcpp::protocol::handler< T >::serialize(), emlabcpp::protocol::serializer< T, Endianess >::serialize_at(), and emlabcpp::view_n().
Member Data Documentation
checksum_size
template<typename Packet > constexpr std::size_t emlabcpp::protocol::packet_handler< Packet >::checksum_size = Packet::checksum_traits::max_size static constexpr
endianess
template<typename Packet > constexpr auto emlabcpp::protocol::packet_handler< Packet >::endianess = Packet::endianess static constexpr
size_offset
template<typename Packet > constexpr std::size_t emlabcpp::protocol::packet_handler< Packet >::size_offset = Packet::prefix_traits::max_size static constexpr
size_size
template<typename Packet > constexpr std::size_t emlabcpp::protocol::packet_handler< Packet >::size_size = Packet::size_traits::max_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/packet_handler.h