emlabcpp: emlabcpp::protocol::converter< std::variant< Ds... >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< std::variant< Ds... >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using def_type = std::variant< Ds... >
using value_type = typename traits_for< def_type >::value_type
using id_type = uint8_t
using id_converter = converter_for< id_type, Endianess >
using size_type = bounded< std::size_t, min_size, max_size >
template<std::size_t I>
using nth_converter = converter_for< std::variant_alternative_t< I, def_type >, Endianess >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< std::byte, max_size > buffer, value_type const &item)
static constexpr conversion_result deserialize (std::span< std::byte const > const &buffer, value_type &value)
Static Public Attributes
static constexpr std::size_t max_size = traits_for< def_type >::max_size
static constexpr std::size_t min_size = traits_for< def_type >::min_size
static constexpr std::size_t id_size = id_converter::max_size
Member Typedef Documentation
def_type
template<convertible... Ds, std::endian Endianess> using emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::def_type = std::variant< Ds... >
id_converter
template<convertible... Ds, std::endian Endianess> using emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::id_converter = converter_for< id_type, Endianess >
id_type
template<convertible... Ds, std::endian Endianess> using emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::id_type = uint8_t
nth_converter
template<convertible... Ds, std::endian Endianess> template<std::size_t I> using emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::nth_converter = converter_for< std::variant_alternative_t< I, def_type >, Endianess >
size_type
template<convertible... Ds, std::endian Endianess> using emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
value_type
template<convertible... Ds, std::endian Endianess> using emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::value_type = typename traits_for< def_type >::value_type
Member Function Documentation
deserialize()
template<convertible... Ds, std::endian Endianess> static constexpr conversion_result emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::deserialize (std::span< std::byte const > const & buffer, value_type & value) inline static constexpr
References emlabcpp::protocol::deserialize(), emlabcpp::res, emlabcpp::protocol::UNDEFVAR_ERR, and emlabcpp::until_index().
serialize_at()
template<convertible... Ds, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::serialize_at (std::span< std::byte, max_size > buffer, value_type const & item) inline static constexpr
this also asserts that id has static serialized size
References emlabcpp::protocol::Endianess, emlabcpp::protocol::max_size, emlabcpp::protocol::serialize_at(), and emlabcpp::visit_index().
Member Data Documentation
id_size
template<convertible... Ds, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::id_size = id_converter::max_size static constexpr
max_size
template<convertible... Ds, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::max_size = traits_for< def_type >::max_size static constexpr
min_size
template<convertible... Ds, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< std::variant< Ds... >, Endianess >::min_size = traits_for< def_type >::min_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h