emlabcpp: emlabcpp::request_reply< RequestType, ReplyType >::promise_type Struct Reference
emlabcpp::request_reply< RequestType, ReplyType >::promise_type Struct Reference
#include <request_reply.h>
Public Member Functions
request_reply get_return_object ()
std::suspend_never initial_suspend ()
std::suspend_always final_suspend () noexcept
void unhandled_exception ()
void return_void ()
awaiter yield_value (ReplyType out)
void * operator new (std::size_t sz, auto &, pool_interface *pi, auto &&...)
void * operator new (std::size_t sz, pool_interface *pi, auto &&...)
void operator delete (void *ptr, std::size_t)
Static Public Member Functions
static void * alloc (std::size_t sz, pool_interface *pi)
Public Attributes
std::optional< RequestType > request
std::optional< ReplyType > reply
Static Public Attributes
static constexpr std::size_t ptr_size = sizeof(pool_interface*)
Member Function Documentation
alloc()
template<typename RequestType , typename ReplyType > static void* emlabcpp::request_reply< RequestType, ReplyType >::promise_type::alloc (std::size_t sz, pool_interface * pi) inline static
References emlabcpp::pi, and emlabcpp::request_reply< RequestType, ReplyType >::promise_type::ptr_size.
final_suspend()
template<typename RequestType , typename ReplyType > std::suspend_always emlabcpp::request_reply< RequestType, ReplyType >::promise_type::final_suspend () inline noexcept
get_return_object()
template<typename RequestType , typename ReplyType > request_reply emlabcpp::request_reply< RequestType, ReplyType >::promise_type::get_return_object () inline
initial_suspend()
template<typename RequestType , typename ReplyType > std::suspend_never emlabcpp::request_reply< RequestType, ReplyType >::promise_type::initial_suspend () inline
operator delete()
template<typename RequestType , typename ReplyType > void emlabcpp::request_reply< RequestType, ReplyType >::promise_type::operator delete (void * ptr, std::size_t) inline
References emlabcpp::pool_interface::deallocate().
operator new() [1/2]
template<typename RequestType , typename ReplyType > void* emlabcpp::request_reply< RequestType, ReplyType >::promise_type::operator new (std::size_t sz, auto & , pool_interface * pi, auto && ...) inline
References emlabcpp::request_reply< RequestType, ReplyType >::promise_type::alloc(), and emlabcpp::pi.
operator new() [2/2]
template<typename RequestType , typename ReplyType > void* emlabcpp::request_reply< RequestType, ReplyType >::promise_type::operator new (std::size_t sz, pool_interface * pi, auto && ...) inline
References emlabcpp::request_reply< RequestType, ReplyType >::promise_type::alloc(), and emlabcpp::pi.
return_void()
template<typename RequestType , typename ReplyType > void emlabcpp::request_reply< RequestType, ReplyType >::promise_type::return_void () inline
unhandled_exception()
template<typename RequestType , typename ReplyType > void emlabcpp::request_reply< RequestType, ReplyType >::promise_type::unhandled_exception () inline
yield_value()
template<typename RequestType , typename ReplyType > awaiter emlabcpp::request_reply< RequestType, ReplyType >::promise_type::yield_value (ReplyType out) inline
References emlabcpp::request_reply< RequestType, ReplyType >::promise_type::reply.
Member Data Documentation
ptr_size
template<typename RequestType , typename ReplyType > constexpr std::size_t emlabcpp::request_reply< RequestType, ReplyType >::promise_type::ptr_size = sizeof(pool_interface*) static constexpr
reply
template<typename RequestType , typename ReplyType > std::optional< ReplyType > emlabcpp::request_reply< RequestType, ReplyType >::promise_type::reply
request
template<typename RequestType , typename ReplyType > std::optional< RequestType > emlabcpp::request_reply< RequestType, ReplyType >::promise_type::request
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/coroutine/request_reply.h