emlabcpp: emlabcpp::protocol::converter< static_vector< T, N >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< static_vector< T, N >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using value_type = typename traits_for< static_vector< T, N > >::value_type
using counter_type = typename traits_for< static_vector< T, N > >::counter_type
using counter_converter = converter_for< counter_type, Endianess >
using sub_converter = converter_for< T, Endianess >
using size_type = bounded< std::size_t, min_size, max_size >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< std::byte, max_size > buffer, const value_type &item)
static constexpr conversion_result deserialize (const std::span< const std::byte > &buffer, value_type &value)
Static Public Attributes
static constexpr std::size_t counter_size = counter_converter::max_size
static constexpr std::size_t max_size = traits_for< static_vector< T, N > >::max_size
static constexpr std::size_t min_size = traits_for< static_vector< T, N > >::min_size
Member Typedef Documentation
counter_converter
template<typename T , std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::counter_converter = converter_for< counter_type, Endianess >
counter_type
template<typename T , std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::counter_type = typename traits_for< static_vector< T, N > >::counter_type
size_type
template<typename T , std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
sub_converter
template<typename T , std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::sub_converter = converter_for< T, Endianess >
value_type
template<typename T , std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::value_type = typename traits_for< static_vector< T, N > >::value_type
Member Function Documentation
deserialize()
template<typename T , std::size_t N, std::endian Endianess> static constexpr conversion_result emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::deserialize (const std::span< const std::byte > & buffer, value_type & value) inline static constexpr
References emlabcpp::count(), emlabcpp::protocol::deserialize(), and emlabcpp::res.
serialize_at()
template<typename T , std::size_t N, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::serialize_at (std::span< std::byte, max_size > buffer, const value_type & item) inline static constexpr
References EMLABCPP_ASSERT, emlabcpp::bounded< T, MinVal, MaxVal >::make(), and emlabcpp::protocol::serialize_at().
Member Data Documentation
counter_size
template<typename T , std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::counter_size = counter_converter::max_size static constexpr
max_size
template<typename T , std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::max_size = traits_for< static_vector< T, N > >::max_size static constexpr
min_size
template<typename T , std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< static_vector< T, N >, Endianess >::min_size = traits_for< static_vector< T, N > >::min_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h