emlabcpp: emlabcpp::protocol::register_handler< Map > Struct Template Reference
emlabcpp::protocol::register_handler< Map > Struct Template Reference
Handler for serialization and extraction of datatypes used by the register_map.
#include <register_handler.h>
Public Types
using map_type = Map
using key_type = typename map_type::key_type
using message_type = typename map_type::message_type
template<key_type Key>
using reg_value_type = typename map_type::template reg_value_type< Key >
template<key_type Key>
using reg_def_type = typename map_type::template reg_def_type< Key >
Static Public Member Functions
template<key_type Key>
static message_type serialize (reg_value_type< Key > val)
static message_type select (map_type const &m, key_type key)
template<key_type Key>
static std::variant< reg_value_type< Key >, error_record > extract (view< std::byte const * > const &msg)
static std::optional< error_record > insert (map_type &m, key_type key, view< std::byte const * > const &buff)
Static Public Attributes
static constexpr std::size_t max_size = map_type::max_value_size
Detailed Description
template<typename Map>
struct emlabcpp::protocol::register_handler< Map >
Handler for serialization and extraction of datatypes used by the register_map.
This provides interface for handling conversion of bytes to types used in the map. serialize and extract works directly with the types used by the map, based on compile time key. select and insert works with the map itself based on runtime information.
Member Typedef Documentation
key_type
template<typename Map > using emlabcpp::protocol::register_handler< Map >::key_type = typename map_type::key_type
map_type
template<typename Map > using emlabcpp::protocol::register_handler< Map >::map_type = Map
message_type
template<typename Map > using emlabcpp::protocol::register_handler< Map >::message_type = typename map_type::message_type
reg_def_type
template<typename Map > template<key_type Key> using emlabcpp::protocol::register_handler< Map >::reg_def_type = typename map_type::template reg_def_type< Key >
reg_value_type
template<typename Map > template<key_type Key> using emlabcpp::protocol::register_handler< Map >::reg_value_type = typename map_type::template reg_value_type< Key >
Member Function Documentation
extract()
template<typename Map > template<key_type Key> static std::variant< reg_value_type< Key >, error_record > emlabcpp::protocol::register_handler< Map >::extract (view< std::byte const * > const & msg) inline static
References emlabcpp::view< Iterator, EndIterator >::begin(), emlabcpp::protocol::deserialize(), emlabcpp::bounded_view< Iterator, SizeType >::make(), emlabcpp::protocol::max_size, emlabcpp::min(), emlabcpp::res, emlabcpp::view< Iterator, EndIterator >::size(), emlabcpp::protocol::SIZE_ERR, and emlabcpp::view_n().
insert()
template<typename Map > static std::optional< error_record > emlabcpp::protocol::register_handler< Map >::insert (map_type & m, key_type key, view< std::byte const * > const & buff) inline static
References emlabcpp::match(), and emlabcpp::res.
select()
template<typename Map > static message_type emlabcpp::protocol::register_handler< Map >::select (map_type const & m, key_type key) inline static
serialize()
template<typename Map > template<key_type Key> static message_type emlabcpp::protocol::register_handler< Map >::serialize (reg_value_type< Key > val) inline static
References emlabcpp::protocol::register_handler< Map >::max_size, emlabcpp::res, and emlabcpp::protocol::serialize_at().
Member Data Documentation
max_size
template<typename Map > constexpr std::size_t emlabcpp::protocol::register_handler< Map >::max_size = map_type::max_value_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/register_handler.h