emlabcpp: emlabcpp::cfg::update_cbs_bind< T > Struct Template Reference
emlabcpp::cfg::update_cbs_bind< T > Struct Template Reference
#include <handler.h>
Public Member Functions
update_cbs_bind (T &lu)
std::span< std::byte > get_buffer () override
result read (std::size_t addr, std::span< std::byte, cell_size > data) override
result write (std::size_t start_addr, std::span< std::byte > data) override
cache_res check_key_cache (uint32_t key) override
bool value_changed (uint32_t key, std::span< std::byte > data) override
opt< std::size_t > serialize_key (uint32_t key, std::span< std::byte > buffer) override
opt< uint32_t > take_unseen_key () override
result reset_keys () override
Public Member Functions inherited from emlabcpp::cfg::iface_base
virtual ~iface_base ()=default
Public Attributes
T & lu
Constructor & Destructor Documentation
update_cbs_bind()
template<typename T > emlabcpp::cfg::update_cbs_bind< T >::update_cbs_bind (T & lu) inline
Member Function Documentation
check_key_cache()
template<typename T > cache_res emlabcpp::cfg::update_cbs_bind< T >::check_key_cache (uint32_t key) inline override virtual
Implements emlabcpp::cfg::update_iface.
References emlabcpp::cfg::update_cbs_bind< T >::lu.
get_buffer()
template<typename T > std::span< std::byte > emlabcpp::cfg::update_cbs_bind< T >::get_buffer () inline override virtual
Implements emlabcpp::cfg::iface_base.
References emlabcpp::cfg::update_cbs_bind< T >::lu.
read()
template<typename T > result emlabcpp::cfg::update_cbs_bind< T >::read (std::size_t addr, std::span< std::byte, cell_size > data) inline override virtual
Implements emlabcpp::cfg::iface_base.
References emlabcpp::data(), and emlabcpp::cfg::update_cbs_bind< T >::lu.
reset_keys()
template<typename T > result emlabcpp::cfg::update_cbs_bind< T >::reset_keys () inline override virtual
Implements emlabcpp::cfg::update_iface.
References emlabcpp::cfg::update_cbs_bind< T >::lu.
serialize_key()
template<typename T > opt< std::size_t > emlabcpp::cfg::update_cbs_bind< T >::serialize_key (uint32_t key, std::span< std::byte > buffer) inline override virtual
Implements emlabcpp::cfg::update_iface.
References emlabcpp::cfg::update_cbs_bind< T >::lu.
take_unseen_key()
template<typename T > opt< uint32_t > emlabcpp::cfg::update_cbs_bind< T >::take_unseen_key () inline override virtual
Implements emlabcpp::cfg::update_iface.
References emlabcpp::cfg::update_cbs_bind< T >::lu.
value_changed()
template<typename T > bool emlabcpp::cfg::update_cbs_bind< T >::value_changed (uint32_t key, std::span< std::byte > data) inline override virtual
Implements emlabcpp::cfg::update_iface.
References emlabcpp::data(), and emlabcpp::cfg::update_cbs_bind< T >::lu.
write()
template<typename T > result emlabcpp::cfg::update_cbs_bind< T >::write (std::size_t start_addr, std::span< std::byte > data) inline override virtual
Implements emlabcpp::cfg::update_iface.
References emlabcpp::data(), and emlabcpp::cfg::update_cbs_bind< T >::lu.
Member Data Documentation
lu
template<typename T > T& emlabcpp::cfg::update_cbs_bind< T >::lu
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/cfg/handler.h