emlabcpp: emlabcpp::protocol::serializer< T, Endianess > Struct Template Reference
emlabcpp::protocol::serializer< T, Endianess > Struct Template Reference
#include <serializer.h>
Public Types
using size_type = bounded< std::size_t, max_size, max_size >
Static Public Member Functions
static constexpr auto & bget (auto &buffer, const std::size_t i)
static constexpr void serialize_at (std::span< uint8_t, max_size > buffer, T item)
static constexpr T deserialize (const std::span< const uint8_t, max_size > &buffer)
Static Public Attributes
static constexpr std::size_t max_size = sizeof(T)
static constexpr bool is_big_endian = Endianess == std::endian::big
Member Typedef Documentation
size_type
template<base_type T, std::endian Endianess> using emlabcpp::protocol::serializer< T, Endianess >::size_type = bounded< std::size_t, max_size, max_size >
Member Function Documentation
bget()
template<base_type T, std::endian Endianess> static constexpr auto& emlabcpp::protocol::serializer< T, Endianess >::bget (auto & buffer, const std::size_t i) inline static constexpr
References emlabcpp::protocol::serializer< T, Endianess >::is_big_endian, and emlabcpp::protocol::serializer< T, Endianess >::max_size.
deserialize()
template<base_type T, std::endian Endianess> static constexpr T emlabcpp::protocol::serializer< T, Endianess >::deserialize (const std::span< const uint8_t, max_size > & buffer) inline static constexpr
References emlabcpp::protocol::serializer< T, Endianess >::bget(), emlabcpp::protocol::serializer< T, Endianess >::max_size, emlabcpp::range(), and emlabcpp::res.
serialize_at()
template<base_type T, std::endian Endianess> static constexpr void emlabcpp::protocol::serializer< T, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, T item) inline static constexpr
References emlabcpp::protocol::serializer< T, Endianess >::bget(), emlabcpp::protocol::serializer< T, Endianess >::max_size, and emlabcpp::range().
Member Data Documentation
is_big_endian
template<base_type T, std::endian Endianess> constexpr bool emlabcpp::protocol::serializer< T, Endianess >::is_big_endian = Endianess == std::endian::big static constexpr
max_size
template<base_type T, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::serializer< T, Endianess >::max_size = sizeof(T) static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/serializer.h