emlabcpp: emlabcpp::cfg::handler< Payload, Field, Endianess > Struct Template Reference
emlabcpp::cfg::handler< Payload, Field, Endianess > Struct Template Reference
#include <handler.h>
Public Types
using chcksum_conv = protocol::converter_for< checksum, Endianess >
Static Public Member Functions
template<typename ChecksumFunction >
static std::tuple< bool, std::span< std::byte > > store (std::span< std::byte > target_buffer, const Payload &pl, view< const Field * > fields, ChecksumFunction &&chcksm_f)
template<typename FieldFunction , typename ChecksumFunction >
static std::tuple< bool, std::span< std::byte > > store (std::span< std::byte > target_buffer, const Payload &pl, std::size_t field_count, FieldFunction &&field_f, ChecksumFunction &&chcksm_f)
template<typename PayloadFunction , typename FieldFunction , typename ChecksumFunction >
static load_result load (std::span< std::byte > source, PayloadFunction &&pl_f, FieldFunction &&field_f, ChecksumFunction &&chcksm_f)
Member Typedef Documentation
chcksum_conv
template<typename Payload , typename Field , std::endian Endianess> using emlabcpp::cfg::handler< Payload, Field, Endianess >::chcksum_conv = protocol::converter_for< checksum, Endianess >
Member Function Documentation
load()
template<typename Payload , typename Field , std::endian Endianess> template<typename PayloadFunction , typename FieldFunction , typename ChecksumFunction > static load_result emlabcpp::cfg::handler< Payload, Field, Endianess >::load (std::span< std::byte > source, PayloadFunction && pl_f, FieldFunction && field_f, ChecksumFunction && chcksm_f) inline static
References emlabcpp::cfg::DESERIALIZATION_ERROR, EMLABCPP_DEBUG_LOG, emlabcpp::f, emlabcpp::cfg::header::field_count, emlabcpp::cfg::PAYLOAD_REFUSED, emlabcpp::range(), and emlabcpp::cfg::SUCCESS.
store() [1/2]
template<typename Payload , typename Field , std::endian Endianess> template<typename FieldFunction , typename ChecksumFunction > static std::tuple< bool, std::span< std::byte > > emlabcpp::cfg::handler< Payload, Field, Endianess >::store (std::span< std::byte > target_buffer, const Payload & pl, std::size_t field_count, FieldFunction && field_f, ChecksumFunction && chcksm_f) inline static
References emlabcpp::cfg::header::field_count, and emlabcpp::range().
store() [2/2]
template<typename Payload , typename Field , std::endian Endianess> template<typename ChecksumFunction > static std::tuple< bool, std::span< std::byte > > emlabcpp::cfg::handler< Payload, Field, Endianess >::store (std::span< std::byte > target_buffer, const Payload & pl, view< const Field * > fields, ChecksumFunction && chcksm_f) inline static
References emlabcpp::view< Iterator, EndIterator >::size().
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/cfg/handler.h