emlabcpp: emlabcpp::protocol::converter< group< Ds... >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< group< Ds... >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using value_type = typename traits_for< group< Ds... > >::value_type
using def_variant = std::variant< Ds... >
using size_type = bounded< std::size_t, min_size, max_size >
template<std::size_t I>
using nth_converter = converter_for< std::variant_alternative_t< I, def_variant >, Endianess >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< std::byte, max_size > buffer, const value_type &item)
static constexpr conversion_result deserialize (const std::span< const std::byte > &buffer, value_type &value)
Static Public Attributes
static constexpr std::size_t max_size = traits_for< group< Ds... > >::max_size
static constexpr std::size_t min_size = traits_for< group< Ds... > >::min_size
Member Typedef Documentation
def_variant
template<typename... Ds, std::endian Endianess> using emlabcpp::protocol::converter< group< Ds... >, Endianess >::def_variant = std::variant< Ds... >
nth_converter
template<typename... Ds, std::endian Endianess> template<std::size_t I> using emlabcpp::protocol::converter< group< Ds... >, Endianess >::nth_converter = converter_for< std::variant_alternative_t< I, def_variant >, Endianess >
size_type
template<typename... Ds, std::endian Endianess> using emlabcpp::protocol::converter< group< Ds... >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
value_type
template<typename... Ds, std::endian Endianess> using emlabcpp::protocol::converter< group< Ds... >, Endianess >::value_type = typename traits_for< group< Ds... > >::value_type
Member Function Documentation
deserialize()
template<typename... Ds, std::endian Endianess> static constexpr conversion_result emlabcpp::protocol::converter< group< Ds... >, Endianess >::deserialize (const std::span< const std::byte > & buffer, value_type & value) inline static constexpr
References emlabcpp::protocol::deserialize(), emlabcpp::protocol::GROUP_ERR, emlabcpp::res, and emlabcpp::until_index().
serialize_at()
template<typename... Ds, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< group< Ds... >, Endianess >::serialize_at (std::span< std::byte, max_size > buffer, const value_type & item) inline static constexpr
References emlabcpp::protocol::Endianess, emlabcpp::protocol::serialize_at(), and emlabcpp::visit_index().
Member Data Documentation
max_size
template<typename... Ds, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< group< Ds... >, Endianess >::max_size = traits_for< group< Ds... > >::max_size static constexpr
min_size
template<typename... Ds, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< group< Ds... >, Endianess >::min_size = traits_for< group< Ds... > >::min_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h