emlabcpp: emlabcpp::static_storage< T, N > Struct Template Reference
emlabcpp::static_storage< T, N > Struct Template Reference
Continuous data container that can contain N of uninitialized elements.
#include <static_storage.h>
Public Types
using value_type = T
using reference = T &
using const_reference = T const &
using pointer = T *
using const_pointer = T const *
using size_type = std::size_t
Public Member Functions
constexpr pointer data () noexcept
Returns pointer to first item of the storage.
constexpr const_pointer data () const noexcept
Returns pointer to first item of the storage.
template<typename... Args>
constexpr T & emplace_item (size_type const i, Args &&... args) noexcept(std::is_nothrow_constructible_v< T, Args... >)
Constructs an item at position i with arguments args...
constexpr auto copy_n (size_type const i, size_type const n, auto iter) noexcept(std::is_nothrow_copy_constructible_v< T >)
Copies n items from iterator iter to storage starting at position i
constexpr auto move_n (size_type const i, size_type const n, auto iter) noexcept(std::is_nothrow_move_constructible_v< T >)
Moves n items from iterator iter to storage starting at position i
constexpr void delete_n (size_type const i, size_type const n) noexcept(std::is_nothrow_destructible_v< T >)
Deconstructs n items starting at position i.
constexpr void delete_item (size_type const i) noexcept(std::is_nothrow_destructible_v< T >)
Deconstructs an item at position i.
constexpr reference operator[] (size_type const i) noexcept
Provides a reference to item at position i.
constexpr const_reference operator[] (size_type const i) const noexcept
Provides a reference to item at position i.
Static Public Attributes
static constexpr std::size_t capacity = N
Additional Inherited Members
Static Public Member Functions inherited from emlabcpp::static_storage_base
template<typename F , typename T >
static F _copy_n (F first, std::size_t n, T *dest)
template<typename F , typename T >
static F _move_n (F first, std::size_t n, T *dest)
Detailed Description
template<typename T, std::size_t N>
struct emlabcpp::static_storage< T, N >
Continuous data container that can contain N of uninitialized elements.
Bookkeeping (what item is initialized and what is not) is up to owner of this structure.
Member Typedef Documentation
const_pointer
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::const_pointer = T const*
const_reference
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::const_reference = T const&
pointer
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::pointer = T*
reference
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::reference = T&
size_type
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::size_type = std::size_t
value_type
template<typename T , std::size_t N> using emlabcpp::static_storage< T, N >::value_type = T
Member Function Documentation
copy_n()
template<typename T , std::size_t N> constexpr auto emlabcpp::static_storage< T, N >::copy_n (size_type const i, size_type const n, auto iter) inline constexpr noexcept
Copies n items from iterator iter to storage starting at position i
References emlabcpp::static_storage_base::_copy_n(), and emlabcpp::static_storage< T, N >::data().
data() [1/2]
template<typename T , std::size_t N> constexpr const_pointer emlabcpp::static_storage< T, N >::data () const inline constexpr noexcept
Returns pointer to first item of the storage.
data() [2/2]
template<typename T , std::size_t N> constexpr pointer emlabcpp::static_storage< T, N >::data () inline constexpr noexcept
Returns pointer to first item of the storage.
delete_item()
template<typename T , std::size_t N> constexpr void emlabcpp::static_storage< T, N >::delete_item (size_type const i) inline constexpr noexcept
Deconstructs an item at position i.
References emlabcpp::static_storage< T, N >::data().
delete_n()
template<typename T , std::size_t N> constexpr void emlabcpp::static_storage< T, N >::delete_n (size_type const i, size_type const n) inline constexpr noexcept
Deconstructs n items starting at position i.
References emlabcpp::static_storage< T, N >::data().
emplace_item()
template<typename T , std::size_t N> template<typename... Args> constexpr T& emlabcpp::static_storage< T, N >::emplace_item (size_type const i, Args &&... args) inline constexpr noexcept
Constructs an item at position i with arguments args...
References emlabcpp::args, and emlabcpp::static_storage< T, N >::data().
move_n()
template<typename T , std::size_t N> constexpr auto emlabcpp::static_storage< T, N >::move_n (size_type const i, size_type const n, auto iter) inline constexpr noexcept
Moves n items from iterator iter to storage starting at position i
References emlabcpp::static_storage_base::_move_n(), and emlabcpp::static_storage< T, N >::data().
operator[]() [1/2]
template<typename T , std::size_t N> constexpr const_reference emlabcpp::static_storage< T, N >::operator[] (size_type const i) const inline constexpr noexcept
Provides a reference to item at position i.
References emlabcpp::static_storage< T, N >::data().
operator[]() [2/2]
template<typename T , std::size_t N> constexpr reference emlabcpp::static_storage< T, N >::operator[] (size_type const i) inline constexpr noexcept
Provides a reference to item at position i.
References emlabcpp::static_storage< T, N >::data().
Member Data Documentation
capacity
template<typename T , std::size_t N> constexpr std::size_t emlabcpp::static_storage< T, N >::capacity = N static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/static_storage.h