emlabcpp: emlabcpp::cfg::next_page_locator Struct Reference
emlabcpp::cfg::next_page_locator Struct Reference
#include <handler.h>
Public Member Functions
bool check_page (std::size_t i, std::byte data[2]) noexcept
std::pair< std::size_t, hdr_state > finish () &&noexcept
Member Function Documentation
check_page()
bool emlabcpp::cfg::next_page_locator::check_page (std::size_t i, std::byte data[2]) inline noexcept
References emlabcpp::cfg::byte_to_hdr(), and emlabcpp::data().
finish()
std::pair< std::size_t, hdr_state > emlabcpp::cfg::next_page_locator::finish () && inline noexcept
References emlabcpp::cfg::A, and emlabcpp::cfg::next().
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/cfg2/handler.h