emlabcpp: emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using value_type = typename proto_traits< protocol_sized_buffer< CounterDef, D > >::value_type
using sub_def = converter< D, Endianess >
using counter_def = converter< CounterDef, Endianess >
using counter_size_type = typename counter_def::size_type
using counter_type = typename counter_def::value_type
using size_type = bounded< std::size_t, min_size, max_size >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, const value_type &item)
static constexpr auto deserialize (const bounded_view< const uint8_t *, size_type > &buffer) -> protocol_result< value_type >
Static Public Attributes
static constexpr std::size_t max_size
static constexpr std::size_t counter_size = counter_def::max_size
static constexpr std::size_t min_size = counter_size + sub_def::size_type::min_val
we expect that counter item does not have dynamic size
Member Typedef Documentation
counter_def
template<convertible CounterDef, convertible D, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::counter_def = converter< CounterDef, Endianess >
counter_size_type
template<convertible CounterDef, convertible D, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::counter_size_type = typename counter_def::size_type
counter_type
template<convertible CounterDef, convertible D, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::counter_type = typename counter_def::value_type
size_type
template<convertible CounterDef, convertible D, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
sub_def
template<convertible CounterDef, convertible D, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::sub_def = converter< D, Endianess >
value_type
template<convertible CounterDef, convertible D, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::value_type = typename proto_traits< protocol_sized_buffer< CounterDef, D > >::value_type
Member Function Documentation
deserialize()
template<convertible CounterDef, convertible D, endianess_enum Endianess> static constexpr auto emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::deserialize (const bounded_view< const uint8_t *, size_type > & buffer) -> protocol_result< value_type > inline static constexpr
References emlabcpp::protocol::deserialize(), emlabcpp::bounded_view< Iterator, SizeType >::make(), emlabcpp::res, emlabcpp::protocol::SIZE_ERR, and emlabcpp::view_n().
serialize_at()
template<convertible CounterDef, convertible D, endianess_enum Endianess> static constexpr size_type emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, const value_type & item) inline static constexpr
References emlabcpp::protocol::serialize_at().
Member Data Documentation
counter_size
template<convertible CounterDef, convertible D, endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::counter_size = counter_def::max_size static constexpr
max_size
template<convertible CounterDef, convertible D, endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::max_size static constexpr
Initial value:
=
            proto_traits< protocol_sized_buffer< CounterDef, D > >::max_size
min_size
template<convertible CounterDef, convertible D, endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol::converter< protocol_sized_buffer< CounterDef, D >, Endianess >::min_size = counter_size + sub_def::size_type::min_val static constexpr
we expect that counter item does not have dynamic size
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h