emlabcpp: emlabcpp::protocol::converter< mark, Endianess > Struct Template Reference
emlabcpp::protocol::converter< mark, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using value_type = typename traits_for< mark >::value_type
using size_type = bounded< std::size_t, max_size, max_size >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, value_type item)
static constexpr auto deserialize (const bounded_view< const uint8_t *, size_type > &buffer) -> conversion_result< value_type >
Static Public Attributes
static constexpr std::size_t max_size = traits_for< mark >::max_size
Member Typedef Documentation
size_type
template<std::endian Endianess> using emlabcpp::protocol::converter< mark, Endianess >::size_type = bounded< std::size_t, max_size, max_size >
value_type
template<std::endian Endianess> using emlabcpp::protocol::converter< mark, Endianess >::value_type = typename traits_for< mark >::value_type
Member Function Documentation
deserialize()
template<std::endian Endianess> static constexpr auto emlabcpp::protocol::converter< mark, Endianess >::deserialize (const bounded_view< const uint8_t *, size_type > & buffer) -> conversion_result< value_type > inline static constexpr
References emlabcpp::copy(), emlabcpp::res, and emlabcpp::view_n().
serialize_at()
template<std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< mark, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, value_type item) inline static constexpr
References emlabcpp::copy().
Member Data Documentation
max_size
template<std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< mark, Endianess >::max_size = traits_for< mark >::max_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h