emlabcpp: emlabcpp::protocol_serializer< T, Endianess > Struct Template Reference
emlabcpp::protocol_serializer< T, Endianess > Struct Template Reference
#include <serializer.h>
Public Types
using size_type = bounded< std::size_t, max_size, max_size >
using view_type = bounded_view< const uint8_t *, size_type >
Static Public Member Functions
static constexpr auto & bget (auto &buffer, std::size_t i)
static constexpr void serialize_at (std::span< uint8_t, max_size > buffer, T item)
static constexpr T deserialize (const view_type &buffer)
Static Public Attributes
static constexpr std::size_t max_size = sizeof(T)
static constexpr bool is_big_endian = Endianess == PROTOCOL_BIG_ENDIAN
Member Typedef Documentation
size_type
template<protocol_base_type T, protocol_endianess_enum Endianess> using emlabcpp::protocol_serializer< T, Endianess >::size_type = bounded< std::size_t, max_size, max_size >
view_type
template<protocol_base_type T, protocol_endianess_enum Endianess> using emlabcpp::protocol_serializer< T, Endianess >::view_type = bounded_view< const uint8_t*, size_type >
Member Function Documentation
bget()
template<protocol_base_type T, protocol_endianess_enum Endianess> static constexpr auto& emlabcpp::protocol_serializer< T, Endianess >::bget (auto & buffer, std::size_t i) inline static constexpr
References emlabcpp::protocol_serializer< T, Endianess >::is_big_endian, and emlabcpp::protocol_serializer< T, Endianess >::max_size.
deserialize()
template<protocol_base_type T, protocol_endianess_enum Endianess> static constexpr T emlabcpp::protocol_serializer< T, Endianess >::deserialize (const view_type & buffer) inline static constexpr
References emlabcpp::protocol_serializer< T, Endianess >::bget(), emlabcpp::protocol_serializer< T, Endianess >::max_size, emlabcpp::range(), and emlabcpp::res.
serialize_at()
template<protocol_base_type T, protocol_endianess_enum Endianess> static constexpr void emlabcpp::protocol_serializer< T, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, T item) inline static constexpr
References emlabcpp::protocol_serializer< T, Endianess >::bget(), emlabcpp::protocol_serializer< T, Endianess >::max_size, and emlabcpp::range().
Member Data Documentation
is_big_endian
template<protocol_base_type T, protocol_endianess_enum Endianess> constexpr bool emlabcpp::protocol_serializer< T, Endianess >::is_big_endian = Endianess == PROTOCOL_BIG_ENDIAN static constexpr
max_size
template<protocol_base_type T, protocol_endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol_serializer< T, Endianess >::max_size = sizeof(T) static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/serializer.h