emlabcpp: emlabcpp::protocol_handler< T > Struct Template Reference
emlabcpp::protocol_handler< T > Struct Template Reference
protocol_handler< T > should be used to execute actual serialization and deserealization of protocol definition.
#include <handler.h>
Public Types
using def = protocol_def< T, PROTOCOL_BIG_ENDIAN >
using value_type = typename def::value_type
using message_type = protocol_message< def::max_size >
Static Public Member Functions
static message_type serialize (value_type val)
static either< value_type, protocol_error_record > extract (const view< const uint8_t * > &msg)
Detailed Description
template<protocol_declarable T>
struct emlabcpp::protocol_handler< T >
protocol_handler< T > should be used to execute actual serialization and deserealization of protocol definition.
It provides serialize/extract methods that should be used by the user. You may want to have this class (With the include) to be present in separate .cpp file, as the compile time can be quite heavy.
Member Typedef Documentation
def
template<protocol_declarable T> using emlabcpp::protocol_handler< T >::def = protocol_def< T, PROTOCOL_BIG_ENDIAN >
message_type
template<protocol_declarable T> using emlabcpp::protocol_handler< T >::message_type = protocol_message< def::max_size >
value_type
template<protocol_declarable T> using emlabcpp::protocol_handler< T >::value_type = typename def::value_type
Member Function Documentation
extract()
template<protocol_declarable T> static either< value_type, protocol_error_record > emlabcpp::protocol_handler< T >::extract (const view< const uint8_t * > & msg) inline static
References emlabcpp::view< Iterator >::begin(), emlabcpp::bounded_view< Iterator, SizeType >::make(), emlabcpp::min(), emlabcpp::res, emlabcpp::view< Iterator >::size(), emlabcpp::SIZE_ERR, and emlabcpp::view_n().
serialize()
template<protocol_declarable T> static message_type emlabcpp::protocol_handler< T >::serialize (value_type val) inline static
References EMLABCPP_ASSERT, emlabcpp::protocol_message< N >::make(), and emlabcpp::view_n().
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/handler.h