emlabcpp: emlabcpp::protocol::converter< std::array< D, N >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< std::array< D, N >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using value_type = typename proto_traits< std::array< D, N > >::value_type
using sub_converter = converter< D, Endianess >
using sub_size_type = typename sub_converter::size_type
using size_type = bounded< std::size_t, min_size, max_size >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, const value_type &item)
In both methods, we create the bounded size without properly checking that it the bounded type was made properly (that is, that the provided std::size_t value is in the range).
static constexpr auto deserialize (bounded_view< const uint8_t *, size_type > buffer) -> conversion_result< value_type, error_posib >
Static Public Attributes
static constexpr std::size_t max_size = proto_traits< std::array< D, N > >::max_size
static constexpr std::size_t min_size = proto_traits< std::array< D, N > >::min_size
static constexpr error_possibility_enum error_posib
Member Typedef Documentation
size_type
template<convertible D, std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< std::array< D, N >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
sub_converter
template<convertible D, std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< std::array< D, N >, Endianess >::sub_converter = converter< D, Endianess >
sub_size_type
template<convertible D, std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< std::array< D, N >, Endianess >::sub_size_type = typename sub_converter::size_type
value_type
template<convertible D, std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< std::array< D, N >, Endianess >::value_type = typename proto_traits< std::array< D, N > >::value_type
Member Function Documentation
deserialize()
template<convertible D, std::size_t N, std::endian Endianess> static constexpr auto emlabcpp::protocol::converter< std::array< D, N >, Endianess >::deserialize (bounded_view< const uint8_t *, size_type > buffer) -> conversion_result< value_type, error_posib > inline static constexpr
References emlabcpp::protocol::deserialize(), emlabcpp::protocol::ERROR_POSSIBLE, emlabcpp::range(), emlabcpp::res, and emlabcpp::protocol::SIZE_ERR.
serialize_at()
template<convertible D, std::size_t N, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< std::array< D, N >, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, const value_type & item) inline static constexpr
In both methods, we create the bounded size without properly checking that it the bounded type was made properly (that is, that the provided std::size_t value is in the range).
Thas is ok as long as variant "we advanced the iter only by at max `sub_converter::max_size` `N` times".
References EMLABCPP_ASSERT, emlabcpp::bounded< T, MinVal, MaxVal >::make(), emlabcpp::protocol::max_size, emlabcpp::range(), and emlabcpp::protocol::serialize_at().
Member Data Documentation
error_posib
template<convertible D, std::size_t N, std::endian Endianess> constexpr error_possibility_enum emlabcpp::protocol::converter< std::array< D, N >, Endianess >::error_posib static constexpr
Initial value:
=
            ( fixedly_sized< D > && !erroring_converter< sub_converter > ) ? ERROR_IMPOSSIBLE :
                                                                             ERROR_POSSIBLE
max_size
template<convertible D, std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< std::array< D, N >, Endianess >::max_size = proto_traits< std::array< D, N > >::max_size static constexpr
min_size
template<convertible D, std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< std::array< D, N >, Endianess >::min_size = proto_traits< std::array< D, N > >::min_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h