emlabcpp: emlabcpp::protocol::converter< string_buffer< N >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< string_buffer< N >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using traits = traits_for< string_buffer< N > >
using value_type = typename traits::value_type
using size_type = bounded< std::size_t, traits::min_size, max_size >
using counter_type = typename traits::counter_type
using counter_converter = converter_for< counter_type, Endianess >
using sub_converter = converter_for< typename value_type::base_type, Endianess >
Static Public Member Functions
static constexpr size_type serialize_at (const std::span< std::byte, max_size > buffer, const value_type &item)
static constexpr conversion_result deserialize (const std::span< const std::byte > &buffer, value_type &value)
TODO: duplication between this, messages, and static_vector.
Static Public Attributes
static constexpr std::size_t max_size = traits::max_size
static constexpr std::size_t counter_size = counter_converter::max_size
Member Typedef Documentation
counter_converter
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< string_buffer< N >, Endianess >::counter_converter = converter_for< counter_type, Endianess >
counter_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< string_buffer< N >, Endianess >::counter_type = typename traits::counter_type
size_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< string_buffer< N >, Endianess >::size_type = bounded< std::size_t, traits::min_size, max_size >
sub_converter
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< string_buffer< N >, Endianess >::sub_converter = converter_for< typename value_type::base_type, Endianess >
traits
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< string_buffer< N >, Endianess >::traits = traits_for< string_buffer< N > >
value_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< string_buffer< N >, Endianess >::value_type = typename traits::value_type
Member Function Documentation
deserialize()
template<std::size_t N, std::endian Endianess> static constexpr conversion_result emlabcpp::protocol::converter< string_buffer< N >, Endianess >::deserialize (const std::span< const std::byte > & buffer, value_type & value) inline static constexpr
TODO: duplication between this, messages, and static_vector.
References emlabcpp::protocol::BIGSIZE_ERR, emlabcpp::protocol::deserialize(), emlabcpp::protocol::SIZE_ERR, and emlabcpp::protocol::conversion_result::used.
serialize_at()
template<std::size_t N, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< string_buffer< N >, Endianess >::serialize_at (const std::span< std::byte, max_size > buffer, const value_type & item) inline static constexpr
References EMLABCPP_ASSERT, emlabcpp::bounded< T, MinVal, MaxVal >::make(), and emlabcpp::protocol::serialize_at().
Member Data Documentation
counter_size
template<std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< string_buffer< N >, Endianess >::counter_size = counter_converter::max_size static constexpr
max_size
template<std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< string_buffer< N >, Endianess >::max_size = traits::max_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h