emlabcpp: emlabcpp::protocol_def< protocol_group< Ds... >, Endianess > Struct Template Reference
emlabcpp::protocol_def< protocol_group< Ds... >, Endianess > Struct Template Reference
#include <def.h>
Public Types
using value_type = typename protocol_decl< protocol_group< Ds... > >::value_type
using def_variant = std::variant< Ds... >
using size_type = bounded< std::size_t, min_size, max_size >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, const value_type &item)
static constexpr auto deserialize (const bounded_view< const uint8_t *, size_type > &buffer) -> protocol_result< value_type >
Static Public Attributes
static constexpr std::size_t max_size = protocol_decl< protocol_group< Ds... > >::max_size
static constexpr std::size_t min_size
Member Typedef Documentation
def_variant
template<typename... Ds, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::def_variant = std::variant< Ds... >
size_type
template<typename... Ds, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
value_type
template<typename... Ds, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::value_type = typename protocol_decl< protocol_group< Ds... > >::value_type
Member Function Documentation
deserialize()
template<typename... Ds, protocol_endianess_enum Endianess> static constexpr auto emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::deserialize (const bounded_view< const uint8_t *, size_type > & buffer) -> protocol_result< value_type > inline static constexpr
TODO: this pattern repeats mutliple times here
References emlabcpp::GROUP_ERR, emlabcpp::bounded_view< Iterator, SizeType >::make(), emlabcpp::min(), emlabcpp::until_index(), and emlabcpp::view_n().
serialize_at()
template<typename... Ds, protocol_endianess_enum Endianess> static constexpr size_type emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, const value_type & item) inline static constexpr
same check as for std::variant
References EMLABCPP_ASSERT, and emlabcpp::until_index().
Member Data Documentation
max_size
template<typename... Ds, protocol_endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::max_size = protocol_decl< protocol_group< Ds... > >::max_size static constexpr
min_size
template<typename... Ds, protocol_endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol_def< protocol_group< Ds... >, Endianess >::min_size static constexpr
Initial value:
=
            std::min( { protocol_def< Ds, Endianess >::size_type::min_val... } )
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/def.h