emlabcpp: emlabcpp::string_buffer< N > Struct Template Reference
emlabcpp::string_buffer< N > Struct Template Reference
#include <string_buffer.h>
Public Types
using base_type = std::array< char, N >
Public Member Functions
constexpr string_buffer ()
constexpr string_buffer (std::string_view sv)
template<std::size_t M>
constexpr string_buffer (char const (&msg)[M])
template<std::size_t M>
constexpr string_buffer (string_buffer< M > const &msg)
operator std::string_view () const
std::string_view sv () const
constexpr auto begin ()
constexpr auto begin () const
constexpr auto end ()
constexpr auto end () const
constexpr char * data ()
constexpr char const * data () const
constexpr std::size_t size () const
template<std::size_t M>
constexpr auto operator<=> (string_buffer< M > const &other) const noexcept
template<std::size_t M>
constexpr bool operator== (string_buffer< M > const &other) const noexcept
constexpr bool operator== (std::string_view other) const noexcept
string_buffer & extend (std::string_view sv)
Static Public Attributes
static constexpr std::size_t capacity = N
Member Typedef Documentation
base_type
template<std::size_t N> using emlabcpp::string_buffer< N >::base_type = std::array< char, N >
Constructor & Destructor Documentation
string_buffer() [1/4]
template<std::size_t N> constexpr emlabcpp::string_buffer< N >::string_buffer () inline constexpr
References emlabcpp::string_buffer< N >::data(), and emlabcpp::N.
string_buffer() [2/4]
template<std::size_t N> constexpr emlabcpp::string_buffer< N >::string_buffer (std::string_view sv) inline constexpr
References emlabcpp::min(), emlabcpp::N, and emlabcpp::string_buffer< N >::sv().
string_buffer() [3/4]
template<std::size_t N> template<std::size_t M> constexpr emlabcpp::string_buffer< N >::string_buffer (char const (&) msg[M]) inline constexpr
References emlabcpp::string_buffer< N >::begin(), and emlabcpp::N.
string_buffer() [4/4]
template<std::size_t N> template<std::size_t M> constexpr emlabcpp::string_buffer< N >::string_buffer (string_buffer< M > const & msg) inline constexpr
References emlabcpp::string_buffer< N >::data(), and emlabcpp::N.
Member Function Documentation
begin() [1/2]
template<std::size_t N> constexpr auto emlabcpp::string_buffer< N >::begin () inline constexpr
begin() [2/2]
template<std::size_t N> constexpr auto emlabcpp::string_buffer< N >::begin () const inline constexpr
data() [1/2]
template<std::size_t N> constexpr char* emlabcpp::string_buffer< N >::data () inline constexpr
data() [2/2]
template<std::size_t N> constexpr char const* emlabcpp::string_buffer< N >::data () const inline constexpr
end() [1/2]
template<std::size_t N> constexpr auto emlabcpp::string_buffer< N >::end () inline constexpr
end() [2/2]
template<std::size_t N> constexpr auto emlabcpp::string_buffer< N >::end () const inline constexpr
extend()
template<std::size_t N> string_buffer& emlabcpp::string_buffer< N >::extend (std::string_view sv) inline
References emlabcpp::min(), emlabcpp::N, emlabcpp::string_buffer< N >::size(), and emlabcpp::string_buffer< N >::sv().
operator std::string_view()
template<std::size_t N> emlabcpp::string_buffer< N >::operator std::string_view () const inline
References emlabcpp::string_buffer< N >::sv().
operator<=>()
template<std::size_t N> template<std::size_t M> constexpr auto emlabcpp::string_buffer< N >::operator<=> (string_buffer< M > const & other) const inline constexpr noexcept
operator==() [1/2]
template<std::size_t N> constexpr bool emlabcpp::string_buffer< N >::operator== (std::string_view other) const inline constexpr noexcept
operator==() [2/2]
template<std::size_t N> template<std::size_t M> constexpr bool emlabcpp::string_buffer< N >::operator== (string_buffer< M > const & other) const inline constexpr noexcept
size()
template<std::size_t N> constexpr std::size_t emlabcpp::string_buffer< N >::size () const inline constexpr
References emlabcpp::N.
sv()
template<std::size_t N> std::string_view emlabcpp::string_buffer< N >::sv () const inline
References emlabcpp::string_buffer< N >::data(), and emlabcpp::string_buffer< N >::size().
Member Data Documentation
capacity
template<std::size_t N> constexpr std::size_t emlabcpp::string_buffer< N >::capacity = N static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/string_buffer.h