emlabcpp: emlabcpp::protocol_def< static_vector< T, N >, Endianess > Struct Template Reference
emlabcpp::protocol_def< static_vector< T, N >, Endianess > Struct Template Reference
#include <def.h>
Public Types
using value_type = typename protocol_decl< static_vector< T, N > >::value_type
using counter_type = typename protocol_decl< static_vector< T, N > >::counter_type
using counter_def = protocol_def< counter_type, Endianess >
using sub_def = protocol_def< T, Endianess >
using size_type = bounded< std::size_t, min_size, max_size >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, value_type item)
static constexpr auto deserialize (bounded_view< const uint8_t *, size_type > buffer) -> protocol_result< value_type >
Static Public Attributes
static constexpr std::size_t counter_size = counter_def::max_size
static constexpr std::size_t max_size = protocol_decl< static_vector< T, N > >::max_size
static constexpr std::size_t min_size = counter_size
Member Typedef Documentation
counter_def
template<typename T , std::size_t N, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< static_vector< T, N >, Endianess >::counter_def = protocol_def< counter_type, Endianess >
counter_type
template<typename T , std::size_t N, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< static_vector< T, N >, Endianess >::counter_type = typename protocol_decl< static_vector< T, N > >::counter_type
size_type
template<typename T , std::size_t N, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< static_vector< T, N >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
sub_def
template<typename T , std::size_t N, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< static_vector< T, N >, Endianess >::sub_def = protocol_def< T, Endianess >
value_type
template<typename T , std::size_t N, protocol_endianess_enum Endianess> using emlabcpp::protocol_def< static_vector< T, N >, Endianess >::value_type = typename protocol_decl< static_vector< T, N > >::value_type
Member Function Documentation
deserialize()
template<typename T , std::size_t N, protocol_endianess_enum Endianess> static constexpr auto emlabcpp::protocol_def< static_vector< T, N >, Endianess >::deserialize (bounded_view< const uint8_t *, size_type > buffer) -> protocol_result< value_type > inline static constexpr
References emlabcpp::ignore(), emlabcpp::range(), emlabcpp::res, and emlabcpp::SIZE_ERR.
serialize_at()
template<typename T , std::size_t N, protocol_endianess_enum Endianess> static constexpr size_type emlabcpp::protocol_def< static_vector< T, N >, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, value_type item) inline static constexpr
TODO: this duplicates std::array, generalize?
References EMLABCPP_ASSERT, and emlabcpp::range().
Member Data Documentation
counter_size
template<typename T , std::size_t N, protocol_endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol_def< static_vector< T, N >, Endianess >::counter_size = counter_def::max_size static constexpr
max_size
template<typename T , std::size_t N, protocol_endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol_def< static_vector< T, N >, Endianess >::max_size = protocol_decl< static_vector< T, N > >::max_size static constexpr
min_size
template<typename T , std::size_t N, protocol_endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol_def< static_vector< T, N >, Endianess >::min_size = counter_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/def.h