emlabcpp: emlabcpp::cfg::page_loader< KeyCache > Struct Template Reference
emlabcpp::cfg::page_loader< KeyCache > Struct Template Reference
#include <handler.h>
Public Member Functions
page_loader (std::size_t end_addr, KeyCache &key_cache, std::span< std::byte > buffer)
std::size_t addr_to_read () const noexcept
bool errored () const
void on_cell (std::span< std::byte, cell_size > c, std::invocable< uint32_t, std::span< std::byte > > auto &&on_kval)
template<typename M >
std::span< std::byte > on_cell_update (std::span< std::byte, cell_size > c, M &map)
template<typename M >
void on_cell_load (std::span< std::byte, cell_size > c, M &map)
Constructor & Destructor Documentation
page_loader()
template<typename KeyCache > emlabcpp::cfg::page_loader< KeyCache >::page_loader (std::size_t end_addr, KeyCache & key_cache, std::span< std::byte > buffer) inline
Member Function Documentation
addr_to_read()
template<typename KeyCache > std::size_t emlabcpp::cfg::page_loader< KeyCache >::addr_to_read () const inline noexcept
errored()
template<typename KeyCache > bool emlabcpp::cfg::page_loader< KeyCache >::errored () const inline
on_cell()
template<typename KeyCache > void emlabcpp::cfg::page_loader< KeyCache >::on_cell (std::span< std::byte, cell_size > c, std::invocable< uint32_t, std::span< std::byte > > auto && on_kval) inline
References emlabcpp::cfg::deser_cell(), emlabcpp::match(), and emlabcpp::cfg::SEEN.
on_cell_load()
template<typename KeyCache > template<typename M > void emlabcpp::cfg::page_loader< KeyCache >::on_cell_load (std::span< std::byte, cell_size > c, M & map) inline
References emlabcpp::data(), and emlabcpp::cfg::page_loader< KeyCache >::on_cell().
on_cell_update()
template<typename KeyCache > template<typename M > std::span< std::byte > emlabcpp::cfg::page_loader< KeyCache >::on_cell_update (std::span< std::byte, cell_size > c, M & map) inline
References emlabcpp::data(), emlabcpp::cfg::page_loader< KeyCache >::on_cell(), and emlabcpp::cfg::store_kval().
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/cfg2/handler.h