emlabcpp: emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using decl = proto_traits< protocol_tag_group< Ds... > >
using value_type = typename decl::value_type
using def_variant = std::variant< Ds... >
using size_type = bounded< std::size_t, min_size, max_size >
using sub_type = typename decl::sub_type
using sub_def = converter< sub_type, Endianess >
using sub_value = typename sub_def::value_type
Static Public Member Functions
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, const value_type &item)
static constexpr auto deserialize (const bounded_view< const uint8_t *, size_type > &buffer) -> protocol_result< value_type >
Static Public Attributes
static constexpr std::size_t max_size = decl::max_size
static constexpr std::size_t min_size = decl::min_size
Member Typedef Documentation
decl
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::decl = proto_traits< protocol_tag_group< Ds... > >
def_variant
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::def_variant = std::variant< Ds... >
size_type
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
sub_def
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::sub_def = converter< sub_type, Endianess >
sub_type
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::sub_type = typename decl::sub_type
sub_value
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::sub_value = typename sub_def::value_type
value_type
template<typename... Ds, endianess_enum Endianess> using emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::value_type = typename decl::value_type
Member Function Documentation
deserialize()
template<typename... Ds, endianess_enum Endianess> static constexpr auto emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::deserialize (const bounded_view< const uint8_t *, size_type > & buffer) -> protocol_result< value_type > inline static constexpr
References emlabcpp::protocol::deserialize(), and emlabcpp::visit().
serialize_at()
template<typename... Ds, endianess_enum Endianess> static constexpr size_type emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, const value_type & item) inline static constexpr
same check as for std::variant
References EMLABCPP_ASSERT, emlabcpp::protocol::serialize_at(), and emlabcpp::until_index().
Member Data Documentation
max_size
template<typename... Ds, endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::max_size = decl::max_size static constexpr
min_size
template<typename... Ds, endianess_enum Endianess> constexpr std::size_t emlabcpp::protocol::converter< protocol_tag_group< Ds... >, Endianess >::min_size = decl::min_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h