emlabcpp: emlabcpp::coro::memory_promise< PromiseType > Struct Template Reference
emlabcpp::coro::memory_promise< PromiseType > Struct Template Reference
#include <memory_promise.h>
Public Member Functions
void * operator new (const std::size_t sz, auto &, pmr::memory_resource &pi, auto &&...)
void * operator new (const std::size_t sz, pmr::memory_resource &pi, auto &&...)
void operator delete (void *const ptr, const std::size_t size)
Static Public Member Functions
static void * alloc (std::size_t sz, pmr::memory_resource &pi)
Static Public Attributes
static constexpr std::size_t ptr_size = sizeof(pmr::memory_resource*)
Member Function Documentation
alloc()
template<typename PromiseType > static void* emlabcpp::coro::memory_promise< PromiseType >::alloc (std::size_t sz, pmr::memory_resource & pi) inline static
References emlabcpp::pi, and emlabcpp::coro::memory_promise< PromiseType >::ptr_size.
operator delete()
template<typename PromiseType > void emlabcpp::coro::memory_promise< PromiseType >::operator delete (void *const ptr, const std::size_t size) inline
References emlabcpp::pmr::memory_resource::deallocate(), emlabcpp::coro::memory_promise< PromiseType >::ptr_size, and emlabcpp::pmr::throw_bad_alloc().
operator new() [1/2]
template<typename PromiseType > void* emlabcpp::coro::memory_promise< PromiseType >::operator new (const std::size_t sz, auto & , pmr::memory_resource & pi, auto && ...) inline
References emlabcpp::coro::memory_promise< PromiseType >::alloc(), and emlabcpp::pi.
operator new() [2/2]
template<typename PromiseType > void* emlabcpp::coro::memory_promise< PromiseType >::operator new (const std::size_t sz, pmr::memory_resource & pi, auto && ...) inline
References emlabcpp::coro::memory_promise< PromiseType >::alloc(), and emlabcpp::pi.
Member Data Documentation
ptr_size
template<typename PromiseType > constexpr std::size_t emlabcpp::coro::memory_promise< PromiseType >::ptr_size = sizeof(pmr::memory_resource*) static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/coro/memory_promise.h