emlabcpp: emlabcpp::protocol::converter< D, Endianess > Struct Template Reference
emlabcpp::protocol::converter< D, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using value_type = typename proto_traits< D >::value_type
using size_type = bounded< std::size_t, max_size, max_size >
using value_type = typename proto_traits< D >::value_type
using inner_type = typename D::value_type
using sub_def = converter< inner_type, Endianess >
using size_type = typename sub_def::size_type
Static Public Member Functions
static constexpr auto & bget (auto &buffer, std::size_t i)
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, value_type item)
static constexpr auto deserialize (const bounded_view< const uint8_t *, size_type > &buffer) -> conversion_result< value_type >
static constexpr size_type serialize_at (std::span< uint8_t, max_size > buffer, const value_type &item)
static constexpr auto deserialize (const bounded_view< const uint8_t *, size_type > &buffer) -> conversion_result< value_type >
Static Public Attributes
static constexpr std::size_t max_size = proto_traits< D >::max_size
static constexpr bool is_big_endian = Endianess == std::endian::big
Member Typedef Documentation
inner_type
template<base_type D, std::endian Endianess> using emlabcpp::protocol::converter< D, Endianess >::inner_type = typename D::value_type
size_type [1/2]
template<base_type D, std::endian Endianess> using emlabcpp::protocol::converter< D, Endianess >::size_type = bounded< std::size_t, max_size, max_size >
size_type [2/2]
template<base_type D, std::endian Endianess> using emlabcpp::protocol::converter< D, Endianess >::size_type = typename sub_def::size_type
sub_def
template<base_type D, std::endian Endianess> using emlabcpp::protocol::converter< D, Endianess >::sub_def = converter< inner_type, Endianess >
value_type [1/2]
template<base_type D, std::endian Endianess> using emlabcpp::protocol::converter< D, Endianess >::value_type = typename proto_traits< D >::value_type
value_type [2/2]
template<base_type D, std::endian Endianess> using emlabcpp::protocol::converter< D, Endianess >::value_type = typename proto_traits< D >::value_type
Member Function Documentation
bget()
template<base_type D, std::endian Endianess> static constexpr auto& emlabcpp::protocol::converter< D, Endianess >::bget (auto & buffer, std::size_t i) inline static constexpr
References emlabcpp::protocol::max_size.
deserialize() [1/2]
template<base_type D, std::endian Endianess> static constexpr auto emlabcpp::protocol::converter< D, Endianess >::deserialize (const bounded_view< const uint8_t *, size_type > & buffer) -> conversion_result< value_type > inline static constexpr
References emlabcpp::protocol::serializer< T, Endianess >::deserialize(), and emlabcpp::protocol::max_size.
deserialize() [2/2]
template<base_type D, std::endian Endianess> static constexpr auto emlabcpp::protocol::converter< D, Endianess >::deserialize (const bounded_view< const uint8_t *, size_type > & buffer) -> conversion_result< value_type > inline static constexpr
References emlabcpp::protocol::deserialize(), and emlabcpp::res.
serialize_at() [1/2]
template<base_type D, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< D, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, const value_type & item) inline static constexpr
References emlabcpp::protocol::serialize_at().
serialize_at() [2/2]
template<base_type D, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< D, Endianess >::serialize_at (std::span< uint8_t, max_size > buffer, value_type item) inline static constexpr
References emlabcpp::protocol::serializer< T, Endianess >::serialize_at().
Member Data Documentation
is_big_endian
template<base_type D, std::endian Endianess> constexpr bool emlabcpp::protocol::converter< D, Endianess >::is_big_endian = Endianess == std::endian::big static constexpr
max_size
template<base_type D, std::endian Endianess> static constexpr std::size_t emlabcpp::protocol::converter< D, Endianess >::max_size = proto_traits< D >::max_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h