emlabcpp: emlabcpp::coro::pool_promise< PromiseType > Struct Template Reference
emlabcpp::coro::pool_promise< PromiseType > Struct Template Reference
#include <pool_promise.h>
Public Member Functions
void * operator new (std::size_t sz, auto &, pool_interface *pi, auto &&...)
void * operator new (std::size_t sz, pool_interface *pi, auto &&...)
void operator delete (void *ptr, std::size_t)
Static Public Member Functions
static void * alloc (std::size_t sz, pool_interface *pi)
Static Public Attributes
static constexpr std::size_t ptr_size = sizeof(pool_interface*)
Member Function Documentation
alloc()
template<typename PromiseType > static void* emlabcpp::coro::pool_promise< PromiseType >::alloc (std::size_t sz, pool_interface * pi) inline static
References emlabcpp::pi, and emlabcpp::coro::pool_promise< PromiseType >::ptr_size.
operator delete()
template<typename PromiseType > void emlabcpp::coro::pool_promise< PromiseType >::operator delete (void * ptr, std::size_t) inline
References emlabcpp::pool_interface::deallocate().
operator new() [1/2]
template<typename PromiseType > void* emlabcpp::coro::pool_promise< PromiseType >::operator new (std::size_t sz, auto & , pool_interface * pi, auto && ...) inline
References emlabcpp::coro::pool_promise< PromiseType >::alloc(), and emlabcpp::pi.
operator new() [2/2]
template<typename PromiseType > void* emlabcpp::coro::pool_promise< PromiseType >::operator new (std::size_t sz, pool_interface * pi, auto && ...) inline
References emlabcpp::coro::pool_promise< PromiseType >::alloc(), and emlabcpp::pi.
Member Data Documentation
ptr_size
template<typename PromiseType > constexpr std::size_t emlabcpp::coro::pool_promise< PromiseType >::ptr_size = sizeof(pool_interface*) static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/experimental/coro/pool_promise.h