emlabcpp: emlabcpp::protocol::converter< message< N >, Endianess > Struct Template Reference
emlabcpp::protocol::converter< message< N >, Endianess > Struct Template Reference
#include <converter.h>
Public Types
using traits_type = traits_for< message< N > >
using value_type = typename traits_type::value_type
using size_type = bounded< std::size_t, min_size, max_size >
using msg_size_type = typename traits_type::msg_size_type
using msg_size_converter = converter_for< msg_size_type, Endianess >
Static Public Member Functions
static constexpr size_type serialize_at (std::span< std::byte, max_size > buffer, const value_type &item)
static constexpr conversion_result deserialize (const std::span< const std::byte > &buffer, value_type &value)
Static Public Attributes
static constexpr std::size_t min_size = traits_type::min_size
static constexpr std::size_t max_size = traits_type::max_size
static constexpr std::size_t msg_size_size = msg_size_converter::max_size
Member Typedef Documentation
msg_size_converter
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< message< N >, Endianess >::msg_size_converter = converter_for< msg_size_type, Endianess >
msg_size_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< message< N >, Endianess >::msg_size_type = typename traits_type::msg_size_type
size_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< message< N >, Endianess >::size_type = bounded< std::size_t, min_size, max_size >
traits_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< message< N >, Endianess >::traits_type = traits_for< message< N > >
value_type
template<std::size_t N, std::endian Endianess> using emlabcpp::protocol::converter< message< N >, Endianess >::value_type = typename traits_type::value_type
Member Function Documentation
deserialize()
template<std::size_t N, std::endian Endianess> static constexpr conversion_result emlabcpp::protocol::converter< message< N >, Endianess >::deserialize (const std::span< const std::byte > & buffer, value_type & value) inline static constexpr
References emlabcpp::protocol::BIGSIZE_ERR, emlabcpp::protocol::deserialize(), emlabcpp::protocol::SIZE_ERR, and emlabcpp::protocol::conversion_result::used.
serialize_at()
template<std::size_t N, std::endian Endianess> static constexpr size_type emlabcpp::protocol::converter< message< N >, Endianess >::serialize_at (std::span< std::byte, max_size > buffer, const value_type & item) inline static constexpr
The size of protocol::message should always be within the 0...N range
References emlabcpp::copy(), EMLABCPP_ASSERT, emlabcpp::bounded< T, MinVal, MaxVal >::make(), and emlabcpp::protocol::serialize_at().
Member Data Documentation
max_size
template<std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< message< N >, Endianess >::max_size = traits_type::max_size static constexpr
min_size
template<std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< message< N >, Endianess >::min_size = traits_type::min_size static constexpr
msg_size_size
template<std::size_t N, std::endian Endianess> constexpr std::size_t emlabcpp::protocol::converter< message< N >, Endianess >::msg_size_size = msg_size_converter::max_size static constexpr
The documentation for this struct was generated from the following file:
include/emlabcpp/protocol/converter.h