
on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string

jobs:
  install_base:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pacman -Syu cmake gcc clang make ninja gtest nlohmann-json which --noconfirm
      - name: Execute
        run: ${{ inputs.cmd }}
