
on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string

jobs:
  install_base:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pacman -Syu cmake gcc clang make ninja gtest nlohmann-json which parallel python-pip --noconfirm
      - name: Install pip
        run: pip install --upgrade conan
      - name: Conan profile
        run: conan profile detect --force
      - name: Execute
        run: ${{ inputs.cmd }}
