name: CMake tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell:
                    bash
        
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: sudo apt install libgtest-dev gcc-10 g++-10 nlohmann-json3-dev libgtest-dev

            - name: Test
              run: make test COVERAGE=1
              env:
                  CC: gcc-10
                  CXX: g++-10

            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()  
              with:
                name: JEST Tests            
                path: ${{runner.workspace}}/build/Testing/*/*.xml
                reporter: jest-junit        
