name: publish

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: prepare output dir
              run: mkdir -p docs/html/

            - uses: DenverCoder1/doxygen-github-pages-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
