name: Tests

on: [push]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                compiler: [gcc, clang]
                preset: [debug, asan, ubsan, release]
        uses: ./.github/workflows/arch_base.yml
        with:
            cmd: CC=${{ matrix.compiler }} CXX=${{ matrix.compiler == 'clang' && 'clang++' || 'g++' }} make test PRESET=${{ matrix.preset }}
    clang_tidy:
        uses: ./.github/workflows/arch_base.yml
        with:
            cmd: CC=clang CXX=clang++ make clang-tidy
    pre-commit:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - uses: pre-commit/action@v3.0.1
