name: Tests

on: [push]

jobs:
    gcc_test:
        uses: koniarik/emlabcpp/.github/workflows/arch_base.yml@main
        with:
            cmd: make test
    gcc_test_undefined:
        uses: koniarik/emlabcpp/.github/workflows/arch_base.yml@main
        with:
            cmd: make test SANITIZER=undefined
    gcc_test_address:
        uses: koniarik/emlabcpp/.github/workflows/arch_base.yml@main
        with:
            cmd: make test SANITIZER=address
    clang_test:
        uses: koniarik/emlabcpp/.github/workflows/arch_base.yml@main
        with:
            cmd: CXX=clang++ CC=clang make test
    clang_tidy:
        uses: koniarik/emlabcpp/.github/workflows/arch_base.yml@main
        with:
            cmd: make clang-tidy
    conan:
        uses: koniarik/emlabcpp/.github/workflows/arch_base.yml@main
        with:
            cmd: make conan
